#### Handling Missing Data

One of the goals
of pandas is to make working with missing data as painless as possible. For example,
all of the descriptive statistics on pandas objects exclude missing data by default.

The way that missing data is represented in pandas objects is somewhat imperfect,
but it is sufficient for most real-world use. For data with float64 dtype, pandas uses
the floating-point value NaN (Not a Number) to represent missing data.

We call this a sentinel value: when present, it indicates a missing (or null) value

In [2]:
import numpy as np

import pandas as pd

In [3]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [4]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In pandas, we’ve adopted a convention used in the R programming language by referring
to missing data as NA, which stands for not available

The built-in Python None value is also treated as NA

In [ ]:
string_data = pd.Series(["aardvark", "artichoke", np.nan,None, "avocado"])
string_data

0     aardvark
1    artichoke
2          NaN
3          NaN
4      avocado
dtype: str

In [6]:
string_data.isna()

0    False
1    False
2     True
3     True
4    False
dtype: bool

In [7]:
float_data = pd.Series([1, 2, None], dtype='float64')

float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [8]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [9]:
float_data.dropna()

0    1.0
1    2.0
dtype: float64

In [10]:
float_data.fillna(0)

0    1.0
1    2.0
2    0.0
dtype: float64

In [12]:
float_data.notna()

0     True
1     True
2    False
dtype: bool

With DataFrame objects, there are different ways to remove missing data. You may
want to drop rows or columns that are all NA, or only those rows or columns
containing any NAs at all. dropna by default drops any row containing a missing
value:

In [13]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
[np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [14]:
data.dropna()

     0    1    2
0  1.0  6.5  3.0

Passing how="all" will drop only rows that are all NA:

In [15]:
data.dropna(how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

Keep in mind that these functions return new objects by default and do not modify
the contents of the original object.


To drop columns in the same way, pass
axis="columns":

In [16]:
data[4] = np.nan
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [17]:
data.dropna(axis="columns", how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

Suppose you want to keep only rows containing at most a certain number of missing
observations. You can indicate this with the
thresh argument:

In [19]:
df = pd.DataFrame(np.random.standard_normal(size=(7, 3)))

In [20]:
df

          0         1         2
0  0.140555 -0.975435  1.714974
1 -1.130934 -1.818146 -0.235377
2 -0.427209  0.794065 -0.021179
3  0.139414  1.391283  0.707201
4 -0.866390  0.211320  0.821348
5  0.161391  1.578073  0.303231
6 -0.515096  0.235667  2.083696

In [21]:
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
df

          0         1         2
0  0.140555       NaN       NaN
1 -1.130934       NaN       NaN
2 -0.427209       NaN -0.021179
3  0.139414       NaN  0.707201
4 -0.866390  0.211320  0.821348
5  0.161391  1.578073  0.303231
6 -0.515096  0.235667  2.083696

In [22]:
df.dropna()

          0         1         2
4 -0.866390  0.211320  0.821348
5  0.161391  1.578073  0.303231
6 -0.515096  0.235667  2.083696

In [23]:
df.dropna(thresh=2)

          0         1         2
2 -0.427209       NaN -0.021179
3  0.139414       NaN  0.707201
4 -0.866390  0.211320  0.821348
5  0.161391  1.578073  0.303231
6 -0.515096  0.235667  2.083696

#### Filling Missing Data

In [24]:
df.fillna(0)

          0         1         2
0  0.140555  0.000000  0.000000
1 -1.130934  0.000000  0.000000
2 -0.427209  0.000000 -0.021179
3  0.139414  0.000000  0.707201
4 -0.866390  0.211320  0.821348
5  0.161391  1.578073  0.303231
6 -0.515096  0.235667  2.083696

Calling fillna with a dictionary, you can use a different fill value for each column:

In [25]:
df.fillna({1: 0.5, 2: 0})

          0         1         2
0  0.140555  0.500000  0.000000
1 -1.130934  0.500000  0.000000
2 -0.427209  0.500000 -0.021179
3  0.139414  0.500000  0.707201
4 -0.866390  0.211320  0.821348
5  0.161391  1.578073  0.303231
6 -0.515096  0.235667  2.083696

In [28]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))

df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df

          0         1         2
0  1.778858  1.428199 -0.656906
1 -0.866784  0.135631  1.565762
2 -1.372945       NaN -0.177636
3 -1.049887       NaN  0.661986
4 -1.592044       NaN       NaN
5 -0.421404       NaN       NaN

In [30]:
df.ffill()

          0         1         2
0  1.778858  1.428199 -0.656906
1 -0.866784  0.135631  1.565762
2 -1.372945  0.135631 -0.177636
3 -1.049887  0.135631  0.661986
4 -1.592044  0.135631  0.661986
5 -0.421404  0.135631  0.661986

In [31]:
df.ffill(limit=2)

          0         1         2
0  1.778858  1.428199 -0.656906
1 -0.866784  0.135631  1.565762
2 -1.372945  0.135631 -0.177636
3 -1.049887  0.135631  0.661986
4 -1.592044       NaN  0.661986
5 -0.421404       NaN  0.661986

With fillna you can do lots of other things such as simple data imputation using the
median or mean statistics:

In [32]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [ ]:
data.fillna(data.mean())

###fillna arguments
### value - scalar, dict, Series, or DataFrame
### axis - {0 or ‘index’, 1 or ‘columns’}, default 0
### inplace - bool, default False
### limit - int, default None
### downcast - dict, default None

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

#### Data Transformation

#### Removing Duplicates

In [36]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'] , "k2": [1, 1 ,2, 3, 3, 4 , 4]})
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

The DataFrame method duplicated returns a Boolean Series indicating whether
each row is a duplicate (its column values are exactly equal to those in an earlier row)

In [37]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

Relatedly, drop_duplicates returns a DataFrame with rows where the duplicated
array is False filtered out

In [38]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [40]:
data["v1"] = range(len(data))
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

Suppose we had an additional column of
values and wanted to filter duplicates based only on the
column:
"k1"

In [42]:
data.drop_duplicates(subset=["k1"])
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

#### and
by default keep the first observed value combina
duplicated
drop_duplicates
tion.
Passing
will return the last one:
keep="last"

In [43]:
data.drop_duplicates(["k1", "k2"], keep="last")

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

#### Transforming Data Using a Function or Mapping

For many datasets, we may perform some transformations based on the values in an array, Series, or DataFrame.

In [45]:
data = pd.DataFrame( { "food" : ["bacon", "pulled pork", "bacon", "Pastrami", "corned beef", "Bacon", "pastrami", "honey ham", "nova lox"],
"ounces" : [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [50]:
meat_to_animal = {
"bacon": "pig",
"pulled pork": "pig",
"pastrami": "cow",
"corned beef": "cow",
"honey ham": "pig",
"nova lox": "salmon"
}
data["animal"] = data["food"].map(str.lower).map(meat_to_animal)
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [51]:
pd.Series("bacon").map(meat_to_animal)

0    pig
dtype: str

Step-by-Step Breakdown
1. The Lookup Table (Dictionary)

Python
meat_to_animal = {
    "bacon": "pig",
    "pulled pork": "pig",
    # ... etc ...
}
This is your reference guide. Notice that all the keys (the meats) are written strictly in lowercase.

2. The Target Data
You have a DataFrame called data that contains a column named "food". In the real world, this data is usually messy. It might contain "Bacon", "BACON", or "bacon".

3. The Transformation (str.lower and map)
Because dictionaries in Python are perfectly case-sensitive, looking up "Bacon" will fail if your dictionary only has "bacon".

First, the code converts every item in the "food" column to lowercase.

Then, it uses pandas' .map() method to feed those lowercase strings into your meat_to_animal dictionary, returning the matching animal.

#### We could also have passed a function

In [52]:
def get_animal(name):
    return meat_to_animal[name.lower()]

data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: str

#### Using map is a convenient way to perform element-wise transformations and other data cleaning-related operations

#### Replacing Values

#### Filling in missing data with the fillna method is a special case of more general value replacement. As you’ve already seen, map can be used to modify a subset of values in an object, but replace provides a simpler and more flexible way to do so.

In [59]:
data = pd.Series([1., -999, 2., -999, -1000])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
dtype: float64

The -999 values might be sentinel values for missing data. To replace these with NA
values that pandas understands, we can use replace, producing a new Series:

In [60]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
dtype: float64

If you want to replace multiple values at once, you instead pass a list and then the
substitute value

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
dtype: float64

To use a different replacement for each value, pass a list of substitutes:

In [62]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
dtype: float64

The argument passed can also be a dictionary:

In [63]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
dtype: float64