#### Handling Missing Data

One of the goals
of pandas is to make working with missing data as painless as possible. For example,
all of the descriptive statistics on pandas objects exclude missing data by default.

The way that missing data is represented in pandas objects is somewhat imperfect,
but it is sufficient for most real-world use. For data with float64 dtype, pandas uses
the floating-point value NaN (Not a Number) to represent missing data.

We call this a sentinel value: when present, it indicates a missing (or null) value

In [2]:
import numpy as np

import pandas as pd

In [3]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [4]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In pandas, we’ve adopted a convention used in the R programming language by referring
to missing data as NA, which stands for not available

The built-in Python None value is also treated as NA

In [ ]:
string_data = pd.Series(["aardvark", "artichoke", np.nan,None, "avocado"])
string_data

0     aardvark
1    artichoke
2          NaN
3          NaN
4      avocado
dtype: str

In [6]:
string_data.isna()

0    False
1    False
2     True
3     True
4    False
dtype: bool

In [7]:
float_data = pd.Series([1, 2, None], dtype='float64')

float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [8]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [9]:
float_data.dropna()

0    1.0
1    2.0
dtype: float64

In [10]:
float_data.fillna(0)

0    1.0
1    2.0
2    0.0
dtype: float64

In [12]:
float_data.notna()

0     True
1     True
2    False
dtype: bool

With DataFrame objects, there are different ways to remove missing data. You may
want to drop rows or columns that are all NA, or only those rows or columns
containing any NAs at all. dropna by default drops any row containing a missing
value:

In [13]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
[np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [14]:
data.dropna()

     0    1    2
0  1.0  6.5  3.0

Passing how="all" will drop only rows that are all NA:

In [15]:
data.dropna(how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

Keep in mind that these functions return new objects by default and do not modify
the contents of the original object.


To drop columns in the same way, pass
axis="columns":

In [16]:
data[4] = np.nan
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [17]:
data.dropna(axis="columns", how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

Suppose you want to keep only rows containing at most a certain number of missing
observations. You can indicate this with the
thresh argument:

In [19]:
df = pd.DataFrame(np.random.standard_normal(size=(7, 3)))

In [20]:
df

          0         1         2
0  0.140555 -0.975435  1.714974
1 -1.130934 -1.818146 -0.235377
2 -0.427209  0.794065 -0.021179
3  0.139414  1.391283  0.707201
4 -0.866390  0.211320  0.821348
5  0.161391  1.578073  0.303231
6 -0.515096  0.235667  2.083696

In [21]:
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
df

          0         1         2
0  0.140555       NaN       NaN
1 -1.130934       NaN       NaN
2 -0.427209       NaN -0.021179
3  0.139414       NaN  0.707201
4 -0.866390  0.211320  0.821348
5  0.161391  1.578073  0.303231
6 -0.515096  0.235667  2.083696

In [22]:
df.dropna()

          0         1         2
4 -0.866390  0.211320  0.821348
5  0.161391  1.578073  0.303231
6 -0.515096  0.235667  2.083696

In [23]:
df.dropna(thresh=2)

          0         1         2
2 -0.427209       NaN -0.021179
3  0.139414       NaN  0.707201
4 -0.866390  0.211320  0.821348
5  0.161391  1.578073  0.303231
6 -0.515096  0.235667  2.083696

#### Filling Missing Data

In [24]:
df.fillna(0)

          0         1         2
0  0.140555  0.000000  0.000000
1 -1.130934  0.000000  0.000000
2 -0.427209  0.000000 -0.021179
3  0.139414  0.000000  0.707201
4 -0.866390  0.211320  0.821348
5  0.161391  1.578073  0.303231
6 -0.515096  0.235667  2.083696

Calling fillna with a dictionary, you can use a different fill value for each column:

In [25]:
df.fillna({1: 0.5, 2: 0})

          0         1         2
0  0.140555  0.500000  0.000000
1 -1.130934  0.500000  0.000000
2 -0.427209  0.500000 -0.021179
3  0.139414  0.500000  0.707201
4 -0.866390  0.211320  0.821348
5  0.161391  1.578073  0.303231
6 -0.515096  0.235667  2.083696

In [28]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))

df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df

          0         1         2
0  1.778858  1.428199 -0.656906
1 -0.866784  0.135631  1.565762
2 -1.372945       NaN -0.177636
3 -1.049887       NaN  0.661986
4 -1.592044       NaN       NaN
5 -0.421404       NaN       NaN

In [30]:
df.ffill()

          0         1         2
0  1.778858  1.428199 -0.656906
1 -0.866784  0.135631  1.565762
2 -1.372945  0.135631 -0.177636
3 -1.049887  0.135631  0.661986
4 -1.592044  0.135631  0.661986
5 -0.421404  0.135631  0.661986

In [31]:
df.ffill(limit=2)

          0         1         2
0  1.778858  1.428199 -0.656906
1 -0.866784  0.135631  1.565762
2 -1.372945  0.135631 -0.177636
3 -1.049887  0.135631  0.661986
4 -1.592044       NaN  0.661986
5 -0.421404       NaN  0.661986

With fillna you can do lots of other things such as simple data imputation using the
median or mean statistics:

In [32]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [ ]:
data.fillna(data.mean())

###fillna arguments
### value - scalar, dict, Series, or DataFrame
### axis - {0 or ‘index’, 1 or ‘columns’}, default 0
### inplace - bool, default False
### limit - int, default None
### downcast - dict, default None

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64