#### Handling Missing Data

One of the goals
of pandas is to make working with missing data as painless as possible. For example,
all of the descriptive statistics on pandas objects exclude missing data by default.

The way that missing data is represented in pandas objects is somewhat imperfect,
but it is sufficient for most real-world use. For data with float64 dtype, pandas uses
the floating-point value NaN (Not a Number) to represent missing data.

We call this a sentinel value: when present, it indicates a missing (or null) value

In [1]:
import numpy as np

import pandas as pd

In [2]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [3]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In pandas, we’ve adopted a convention used in the R programming language by referring
to missing data as NA, which stands for not available

The built-in Python None value is also treated as NA

In [4]:
string_data = pd.Series(["aardvark", "artichoke", np.nan,None, "avocado"])
string_data

0     aardvark
1    artichoke
2          NaN
3          NaN
4      avocado
dtype: str

In [5]:
string_data.isna()

0    False
1    False
2     True
3     True
4    False
dtype: bool

In [6]:
float_data = pd.Series([1, 2, None], dtype='float64')

float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [7]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [8]:
float_data.dropna()

0    1.0
1    2.0
dtype: float64

In [9]:
float_data.fillna(0)

0    1.0
1    2.0
2    0.0
dtype: float64

In [10]:
float_data.notna()

0     True
1     True
2    False
dtype: bool

With DataFrame objects, there are different ways to remove missing data. You may
want to drop rows or columns that are all NA, or only those rows or columns
containing any NAs at all. dropna by default drops any row containing a missing
value:

In [11]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
[np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [12]:
data.dropna()

     0    1    2
0  1.0  6.5  3.0

Passing how="all" will drop only rows that are all NA:

In [13]:
data.dropna(how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

Keep in mind that these functions return new objects by default and do not modify
the contents of the original object.


To drop columns in the same way, pass
axis="columns":

In [14]:
data[4] = np.nan
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [15]:
data.dropna(axis="columns", how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

Suppose you want to keep only rows containing at most a certain number of missing
observations. You can indicate this with the
thresh argument:

In [16]:
df = pd.DataFrame(np.random.standard_normal(size=(7, 3)))

In [17]:
df

          0         1         2
0 -0.022108 -2.871178  0.588088
1  0.114797  0.652444  1.299056
2 -0.033674 -0.442306 -0.035588
3 -1.675177 -0.310460  1.121665
4 -0.420872 -0.166118  1.645282
5 -0.717372 -1.913921 -0.493447
6  0.639951  1.230140  0.048070

In [18]:
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
df

          0         1         2
0 -0.022108       NaN       NaN
1  0.114797       NaN       NaN
2 -0.033674       NaN -0.035588
3 -1.675177       NaN  1.121665
4 -0.420872 -0.166118  1.645282
5 -0.717372 -1.913921 -0.493447
6  0.639951  1.230140  0.048070

In [19]:
df.dropna()

          0         1         2
4 -0.420872 -0.166118  1.645282
5 -0.717372 -1.913921 -0.493447
6  0.639951  1.230140  0.048070

In [20]:
df.dropna(thresh=2)

          0         1         2
2 -0.033674       NaN -0.035588
3 -1.675177       NaN  1.121665
4 -0.420872 -0.166118  1.645282
5 -0.717372 -1.913921 -0.493447
6  0.639951  1.230140  0.048070

#### Filling Missing Data

In [21]:
df.fillna(0)

          0         1         2
0 -0.022108  0.000000  0.000000
1  0.114797  0.000000  0.000000
2 -0.033674  0.000000 -0.035588
3 -1.675177  0.000000  1.121665
4 -0.420872 -0.166118  1.645282
5 -0.717372 -1.913921 -0.493447
6  0.639951  1.230140  0.048070

Calling fillna with a dictionary, you can use a different fill value for each column:

In [22]:
df.fillna({1: 0.5, 2: 0})

          0         1         2
0 -0.022108  0.500000  0.000000
1  0.114797  0.500000  0.000000
2 -0.033674  0.500000 -0.035588
3 -1.675177  0.500000  1.121665
4 -0.420872 -0.166118  1.645282
5 -0.717372 -1.913921 -0.493447
6  0.639951  1.230140  0.048070

In [23]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))

df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df

          0         1         2
0  0.077934 -0.882222  1.055667
1  1.224570  0.138093 -0.121349
2  0.547999       NaN -0.165784
3  0.604087       NaN -0.648093
4  0.417491       NaN       NaN
5 -0.932924       NaN       NaN

In [24]:
df.ffill()

          0         1         2
0  0.077934 -0.882222  1.055667
1  1.224570  0.138093 -0.121349
2  0.547999  0.138093 -0.165784
3  0.604087  0.138093 -0.648093
4  0.417491  0.138093 -0.648093
5 -0.932924  0.138093 -0.648093

In [25]:
df.ffill(limit=2)

          0         1         2
0  0.077934 -0.882222  1.055667
1  1.224570  0.138093 -0.121349
2  0.547999  0.138093 -0.165784
3  0.604087  0.138093 -0.648093
4  0.417491       NaN -0.648093
5 -0.932924       NaN -0.648093

With fillna you can do lots of other things such as simple data imputation using the
median or mean statistics:

In [26]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [27]:
data.fillna(data.mean())

###fillna arguments
### value - scalar, dict, Series, or DataFrame
### axis - {0 or ‘index’, 1 or ‘columns’}, default 0
### inplace - bool, default False
### limit - int, default None
### downcast - dict, default None

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

#### Data Transformation

#### Removing Duplicates

In [28]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'] , "k2": [1, 1 ,2, 3, 3, 4 , 4]})
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

The DataFrame method duplicated returns a Boolean Series indicating whether
each row is a duplicate (its column values are exactly equal to those in an earlier row)

In [29]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

Relatedly, drop_duplicates returns a DataFrame with rows where the duplicated
array is False filtered out

In [30]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [31]:
data["v1"] = range(len(data))
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

Suppose we had an additional column of
values and wanted to filter duplicates based only on the
column:
"k1"

In [32]:
data.drop_duplicates(subset=["k1"])
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

#### and
by default keep the first observed value combina
duplicated
drop_duplicates
tion.
Passing
will return the last one:
keep="last"

In [33]:
data.drop_duplicates(["k1", "k2"], keep="last")

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

#### Transforming Data Using a Function or Mapping

For many datasets, we may perform some transformations based on the values in an array, Series, or DataFrame.

In [34]:
data = pd.DataFrame( { "food" : ["bacon", "pulled pork", "bacon", "Pastrami", "corned beef", "Bacon", "pastrami", "honey ham", "nova lox"],
"ounces" : [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [35]:
meat_to_animal = {
"bacon": "pig",
"pulled pork": "pig",
"pastrami": "cow",
"corned beef": "cow",
"honey ham": "pig",
"nova lox": "salmon"
}
data["animal"] = data["food"].map(str.lower).map(meat_to_animal)
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [36]:
pd.Series("bacon").map(meat_to_animal)

0    pig
dtype: str

Step-by-Step Breakdown
1. The Lookup Table (Dictionary)

Python
meat_to_animal = {
    "bacon": "pig",
    "pulled pork": "pig",
    # ... etc ...
}
This is your reference guide. Notice that all the keys (the meats) are written strictly in lowercase.

2. The Target Data
You have a DataFrame called data that contains a column named "food". In the real world, this data is usually messy. It might contain "Bacon", "BACON", or "bacon".

3. The Transformation (str.lower and map)
Because dictionaries in Python are perfectly case-sensitive, looking up "Bacon" will fail if your dictionary only has "bacon".

First, the code converts every item in the "food" column to lowercase.

Then, it uses pandas' .map() method to feed those lowercase strings into your meat_to_animal dictionary, returning the matching animal.

#### We could also have passed a function

In [37]:
def get_animal(name):
    return meat_to_animal[name.lower()]

data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: str

#### Using map is a convenient way to perform element-wise transformations and other data cleaning-related operations

#### Replacing Values

#### Filling in missing data with the fillna method is a special case of more general value replacement. As you’ve already seen, map can be used to modify a subset of values in an object, but replace provides a simpler and more flexible way to do so.

In [38]:
data = pd.Series([1., -999, 2., -999, -1000])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
dtype: float64

The -999 values might be sentinel values for missing data. To replace these with NA
values that pandas understands, we can use replace, producing a new Series:

In [39]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
dtype: float64

If you want to replace multiple values at once, you instead pass a list and then the
substitute value

To use a different replacement for each value, pass a list of substitutes:

In [40]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
dtype: float64

The argument passed can also be a dictionary:

In [41]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
dtype: float64

#### The data.replace method is distinct from data.str.replace which performs element-wise string substitution. We look at these string methods on Series later in the chapter

#### Renaming Axis Indexes

Like values in a Series, axis labels can be similarly transformed by a function or
mapping of some form to produce new, differently labeled objects. You can also
modify the axes in place without creating a new data structure.

In [42]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
index=['Ohio', 'Colorado', 'New York'],
columns=['one', 'two', 'three', 'four'])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

Like a Series, the axis indexes have a map method:

In [43]:
def transform(x):
    return x.upper()

data.index.map(transform)

Index(['OHIO', 'COLORADO', 'NEW YORK'], dtype='str')

You can assign to the index attribute, modifying the DataFrame in place

In [44]:
data.index = data.index.map(transform)
data

          one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

If you want to create a transformed version of a dataset without modifying the
original, a useful method is rename:

In [45]:
data.rename(index=str.title, columns=str.upper)

          ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

rename can be used in conjunction with a dictionary-like object, providing
new values for a subset of the axis labels

In [46]:
data

          one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [47]:
data.rename(index= { "OHIO": "INDIANA"}, columns= { "three": "peekaboo  "})

          one  two  peekaboo    four
INDIANA     0    1           2     3
COLORADO    4    5           6     7
NEW YORK    8    9          10    11

rename saves you from the chore of copying the DataFrame manually and assigning
new values to its index and columns attributes.

#### Discretization and Binning

Continuous data is often discretized or otherwise separated into “bins” for analysis.

In [48]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
age_categories = pd.cut(ages, bins)
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

The object pandas returns is a special Categorical object. The output you see
describes the bins computed by pandas.cut

Each bin is identified by a special
(unique to pandas) interval value type containing the lower and upper limit of each
bin:

In [49]:
age_categories.codes # this attribute contains the integer codes that correspond to each bin. Integer codes are used to identify the bin for each value in the original Series.

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [50]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [51]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [52]:
age_categories.value_counts()

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In the string representation of an interval, a parenthesis means that the side is open
(exclusive), while the square bracket means it is closed (inclusive). You can change
which side is closed by passing right=False:

In [53]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

You can override the default interval-based bin labeling by passing a list or array to
the labels option:

In [54]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, str): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

If you pass an integer number of bins to
instead of explicit bin edges, it
pandas.cut
will compute equal-length bins based on the minimum and maximum values in the
data. Consider the case of some uniformly distributed data chopped into fourths

In [55]:
data = np.random.uniform(size=20)
data

array([0.57953296, 0.74463764, 0.78783067, 0.81166338, 0.48088264,
       0.7158409 , 0.5604751 , 0.98303967, 0.76818874, 0.40159355,
       0.13994745, 0.86717323, 0.03746156, 0.54518318, 0.48191847,
       0.02486979, 0.28214027, 0.87100124, 0.41491985, 0.2844387 ])

In [56]:
cat= pd.cut(data, 4, precision=2)

#The precision=2 option limits the decimal precision to two digits.

In [57]:
cat.value_counts()

(0.024, 0.26]    3
(0.26, 0.5]      6
(0.5, 0.74]      4
(0.74, 0.98]     7
Name: count, dtype: int64

A closely related function, pandas.qcut, bins the data based on sample quantiles.
Depending on the distribution of the data, using pandas.cut will not usually result in each bin having the same number of data points. Since pandas.qcut uses sample
quantiles instead, you will obtain roughly equally sized bins

In [58]:
data = np.random.standard_normal(1000)

In [59]:
quantiles = pd.qcut(data, 4 , precision=2)
quantiles

[(0.76, 3.05], (-0.68, -0.068], (0.76, 3.05], (0.76, 3.05], (-3.32, -0.68], ..., (-0.068, 0.76], (-0.068, 0.76], (-3.32, -0.68], (-0.068, 0.76], (0.76, 3.05]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.32, -0.68] < (-0.68, -0.068] < (-0.068, 0.76] < (0.76, 3.05]]

In [60]:
quantiles.value_counts()

(-3.32, -0.68]     250
(-0.68, -0.068]    250
(-0.068, 0.76]     250
(0.76, 3.05]       250
Name: count, dtype: int64

Similar to pandas.cut, you can pass your own quantiles (numbers between 0 and 1,
inclusive):

In [61]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-3.307, -1.275]     100
(-1.275, -0.0675]    400
(-0.0675, 1.284]     400
(1.284, 3.054]       100
Name: count, dtype: int64

#### Detecting and Filtering Outliers

Consider a DataFrame with some normally distributed data:

In [62]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

data

            0         1         2         3
0    0.982278 -0.673393 -1.222649 -0.338044
1   -0.244000  0.739165 -0.412319 -0.067708
2    0.280400  2.093065 -0.488420  0.642326
3   -0.095078 -1.975345 -0.907770  1.081175
4    0.044826  0.255851 -0.304325 -1.027128
..        ...       ...       ...       ...
995  2.305981 -0.850598  0.646585 -1.127601
996  0.512555  1.616320  1.200342 -1.118625
997  1.435327  1.142157 -0.671326 -1.225515
998 -0.000656 -2.367116  0.146010 -0.718911
999  0.081893 -0.465558 -0.498150 -1.169937

[1000 rows x 4 columns]

In [63]:
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.002307    -0.017413    -0.006842    -0.043101
std       0.996712     1.024716     0.986094     0.999318
min      -2.890785    -3.373021    -3.403564    -3.212401
25%      -0.682244    -0.703247    -0.665958    -0.714939
50%       0.000669    -0.066925    -0.064940    -0.024826
75%       0.645012     0.651913     0.586151     0.651698
max       3.243953     3.172944     2.726823     3.405698

Suppose you wanted to find values in one of the columns exceeding 3 in absolute
value:

In [64]:
col = data[2]

In [65]:
col[col.abs() > 3]

77   -3.403564
Name: 2, dtype: float64

To select all rows having a value exceeding 3 or –3, you can use the any method on a
Boolean DataFrame:

In [66]:
data[(data.abs()>3).any(axis="columns")]

            0         1         2         3
70   3.190391  0.146184  1.096309 -0.265953
77   0.391122 -0.530671 -3.403564 -1.215789
226 -0.261475 -0.269540  1.600702 -3.035089
273 -1.345037 -3.373021 -0.089269 -0.359824
324  0.914699  2.096608  2.541608 -3.212401
333 -0.224642  3.172944 -0.753075  1.016653
385 -2.238528  0.054712 -1.562317  3.405698
765  1.197712 -0.480836  0.686887 -3.131220
779  3.243953 -0.064217 -0.070696  1.011166

The parentheses around data.abs() > 3 are necessary in order to call the any
method on the result of the comparison operation

Values can be set based on these criteria. Here is code to cap values outside the
interval –3 to 3:

In [69]:
data[data.abs() > 3] = np.sign(data) * 3

In [70]:
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.001873    -0.017213    -0.006439    -0.043128
std       0.995355     1.023035     0.984784     0.996842
min      -2.890785    -3.000000    -3.000000    -3.000000
25%      -0.682244    -0.703247    -0.665958    -0.714939
50%       0.000669    -0.066925    -0.064940    -0.024826
75%       0.645012     0.651913     0.586151     0.651698
max       3.000000     3.000000     2.726823     3.000000

The statement np.sign(data) produces 1 and –1 values based on whether the values
in data are positive or negative:

In [71]:
np.sign(data).head()

     0    1    2    3
0  1.0 -1.0 -1.0 -1.0
1 -1.0  1.0 -1.0 -1.0
2  1.0  1.0 -1.0  1.0
3 -1.0 -1.0 -1.0  1.0
4  1.0  1.0 -1.0 -1.0

#### Permutation and Random Sampling