In [2]:
import pandas as pd
import numpy as np

In [3]:
sf_file_path = "/Users/navneetsrivastava/Downloads/projects/pyspark_prac/data/Fire_Incidents_20261013.csv"
df = pd.read_csv(sf_file_path,keep_default_na=False,na_filter=False) 

df.head()

/var/folders/ft/l9mh6cgx0jj0zxzptbybbspr0000gn/T/ipykernel_71472/1923689723.py:2: DtypeWarning: Columns (0: zipcode, 1: Station Area, 2: Box, 3: Suppression Units, 4: Suppression Personnel, 5: Other Units, 6: Other Personnel) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(sf_file_path,keep_default_na=False,na_filter=False)

,Incident Number,Exposure Number,ID,Address,Incident Date,Call Number,Alarm DtTm,Arrival DtTm,Close DtTm,City,...,Automatic Extinguishing System Present,Automatic Extinguishing Sytem Type,Automatic Extinguishing Sytem Perfomance,Automatic Extinguishing Sytem Failure Reason,Number of Sprinkler Heads Operating,Supervisor District,neighborhood_district,point,data_as_of,data_loaded_at
0,8038138,0,80381380,334 Mason St.,2008/05/03,81240295,2008/05/03 05:16:49 PM,2008/05/03 05:21:52 PM,2008/05/03 05:21:52 PM,SF,...,,,,,,3,Tenderloin,POINT (-122.40971 37.786758),2008/05/04 07:03:59 AM,2026/09/30 02:27:09 AM
1,8038143,0,80381430,360 Laguna Honda Bl.,2008/05/03,81240300,2008/05/03 05:41:08 PM,2008/05/03 05:51:03 PM,2008/05/03 06:22:16 PM,SF,...,,,,,,7,West of Twin Peaks,POINT (-122.458802 37.747952),2008/05/03 07:20:46 PM,2026/09/30 02:27:09 AM
2,8038144,0,80381440,4054 20th St.,2008/05/03,81240301,2008/05/03 05:54:28 PM,2008/05/03 05:58:02 PM,2008/05/03 07:21:41 PM,SF,...,,,,,0,8,Castro/Upper Market,POINT (-122.43152884 37.75812345),2008/05/23 12:08:15 PM,2026/09/30 02:27:09 AM
3,8038146,0,80381460,1150 Columbus Av.,2008/05/03,81240304,2008/05/03 05:58:03 PM,2008/05/03 06:01:39 PM,2008/05/03 06:05:39 PM,SF,...,,,,,,3,North Beach,POINT (-122.416085817 37.804833),2008/05/03 06:24:04 PM,2026/09/30 02:27:09 AM
4,8038157,0,80381570,25th St. / Harrison St.,2008/05/03,81240318,2008/05/03 06:49:56 PM,2008/05/03 06:53:50 PM,2008/05/03 06:55:01 PM,SF,...,,,,,,9,Mission,POINT (-122.411747 37.751035),2008/05/03 09:27:03 PM,2026/09/30 02:27:09 AM

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 733061 entries, 0 to 733060
Data columns (total 66 columns):
 #   Column                                        Non-Null Count   Dtype
---  ------                                        --------------   -----
 0   Incident Number                               733061 non-null  int64
 1   Exposure Number                               733061 non-null  int64
 2   ID                                            733061 non-null  int64
 3   Address                                       733061 non-null  str
 4   Incident Date                                 733061 non-null  str
 5   Call Number                                   733061 non-null  int64
 6   Alarm DtTm                                    733061 non-null  str
 7   Arrival DtTm                                  733061 non-null  str
 8   Close DtTm                                    733061 non-null  str
 9   City                                          733061 non-null  str
 10  zipcode                                       733061 non-null  object
 11  Battalion                                     733061 non-null  str
 12  Station Area                                  733061 non-null  object
 13  Box                                           733061 non-null  object
 14  Suppression Units                             733061 non-null  object
 15  Suppression Personnel                         733061 non-null  object
 16  EMS Units                                     733061 non-null  int64
 17  EMS Personnel                                 733061 non-null  int64
 18  Other Units                                   733061 non-null  object
 19  Other Personnel                               733061 non-null  object
 20  First Unit On Scene                           733061 non-null  str
 21  Estimated Property Loss                       733061 non-null  str
 22  Estimated Contents Loss                       733061 non-null  str
 23  Fire Fatalities                               733061 non-null  int64
 24  Fire Injuries                                 733061 non-null  int64
 25  Civilian Fatalities                           733061 non-null  int64
 26  Civilian Injuries                             733061 non-null  int64
 27  Number of Alarms                              733061 non-null  int64
 28  Primary Situation                             733061 non-null  str
 29  Mutual Aid                                    733061 non-null  str
 30  Action Taken Primary                          733061 non-null  str
 31  Action Taken Secondary                        733061 non-null  str
 32  Action Taken Other                            733061 non-null  str
 33  Detector Alerted Occupants                    733061 non-null  str
 34  Property Use                                  733061 non-null  str
 35  Area of Fire Origin                           733061 non-null  str
 36  Ignition Cause                                733061 non-null  str
 37  Ignition Factor Primary                       733061 non-null  str
 38  Ignition Factor Secondary                     733061 non-null  str
 39  Heat Source                                   733061 non-null  str
 40  Item First Ignited                            733061 non-null  str
 41  Human Factors Associated with Ignition        733061 non-null  str
 42  Structure Type                                733061 non-null  str
 43  Structure Status                              733061 non-null  str
 44  Floor of Fire Origin                          733061 non-null  str
 45  Fire Spread                                   733061 non-null  str
 46  No Flame Spread                               733061 non-null  str
 47  Number of floors with minimum damage          733061 non-null  str
 48  Number of floors with significant damage      733061 non-null  str
 49  Number of floors with heavy damage            733061 non-null  str
 50  Number of floors with extreme damage          733061 non-null  str
 51  Detectors Present                             733061 non-null  str
 52  Detector Type                                 733061 non-null  str
 53  Detector Operation                            733061 non-null  str
 54  Detector Effectiveness                        733061 non-null  str
 55  Detector Failure Reason                       733061 non-null  str
 56  Automatic Extinguishing System Present        733061 non-null  str
 57  Automatic Extinguishing Sytem Type            733061 non-null  str
 58  Automatic Extinguishing Sytem Perfomance      733061 non-null  str
 59  Automatic Extinguishing Sytem Failure Reason  733061 non-null  str
 60  Number of Sprinkler Heads Operating           733061 non-null  str
 61  Supervisor District                           733061 non-null  str
 62  neighborhood_district                         733061 non-null  str
 63  point                                         733061 non-null  str
 64  data_as_of                                    733061 non-null  str
 65  data_loaded_at                                733061 non-null  str
dtypes: int64(11), object(7), str(48)
memory usage: 578.6+ MB

In [5]:
df.describe()

,Incident Number,Exposure Number,ID,Call Number,EMS Units,EMS Personnel,Fire Fatalities,Fire Injuries,Civilian Fatalities,Civilian Injuries,Number of Alarms
count,7.330610e+05,733061.000000,7.330610e+05,7.330610e+05,733061.000000,733061.000000,733061.000000,733061.000000,733061.000000,733061.000000,733061.000000
mean,1.457236e+07,0.000522,1.457236e+08,1.468749e+08,0.193531,0.353275,0.000003,0.000224,0.000063,0.001033,1.001119
std,6.757052e+06,0.032131,6.757052e+07,6.744440e+07,0.995200,1.147499,0.002336,0.022221,0.008895,0.059374,0.043781
min,3.000001e+06,0.000000,3.000001e+07,3.001000e+07,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,9.025865e+06,0.000000,9.025865e+07,9.088010e+07,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
50%,1.503935e+07,0.000000,1.503935e+08,1.510417e+08,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,2.014805e+07,0.000000,2.014805e+08,2.036203e+08,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,2.613580e+07,7.000000,2.613580e+08,2.626703e+08,574.000000,312.000000,2.000000,9.000000,3.000000,24.000000,5.000000

In [6]:
df.columns

Index(['Incident Number', 'Exposure Number', 'ID', 'Address', 'Incident Date',
       'Call Number', 'Alarm DtTm', 'Arrival DtTm', 'Close DtTm', 'City',
       'zipcode', 'Battalion', 'Station Area', 'Box', 'Suppression Units',
       'Suppression Personnel', 'EMS Units', 'EMS Personnel', 'Other Units',
       'Other Personnel', 'First Unit On Scene', 'Estimated Property Loss',
       'Estimated Contents Loss', 'Fire Fatalities', 'Fire Injuries',
       'Civilian Fatalities', 'Civilian Injuries', 'Number of Alarms',
       'Primary Situation', 'Mutual Aid', 'Action Taken Primary',
       'Action Taken Secondary', 'Action Taken Other',
       'Detector Alerted Occupants', 'Property Use', 'Area of Fire Origin',
       'Ignition Cause', 'Ignition Factor Primary',
       'Ignition Factor Secondary', 'Heat Source', 'Item First Ignited',
       'Human Factors Associated with Ignition', 'Structure Type',
       'Structure Status', 'Floor of Fire Origin', 'Fire Spread',
       'No Flame Spread', 'Number of floors with minimum damage',
       'Number of floors with significant damage',
       'Number of floors with heavy damage',
       'Number of floors with extreme damage', 'Detectors Present',
       'Detector Type', 'Detector Operation', 'Detector Effectiveness',
       'Detector Failure Reason', 'Automatic Extinguishing System Present',
       'Automatic Extinguishing Sytem Type',
       'Automatic Extinguishing Sytem Perfomance',
       'Automatic Extinguishing Sytem Failure Reason',
       'Number of Sprinkler Heads Operating', 'Supervisor District',
       'neighborhood_district', 'point', 'data_as_of', 'data_loaded_at'],
      dtype='str')

In [7]:
new_col =  [
    "".join(["_" + char.lower() if char.isupper() else str.rstrip(char) for char in s]).lstrip("_")
    for s in df.columns
]
new_col

['incident_number',
 'exposure_number',
 'i_d',
 'address',
 'incident_date',
 'call_number',
 'alarm_dt_tm',
 'arrival_dt_tm',
 'close_dt_tm',
 'city',
 'zipcode',
 'battalion',
 'station_area',
 'box',
 'suppression_units',
 'suppression_personnel',
 'e_m_s_units',
 'e_m_s_personnel',
 'other_units',
 'other_personnel',
 'first_unit_on_scene',
 'estimated_property_loss',
 'estimated_contents_loss',
 'fire_fatalities',
 'fire_injuries',
 'civilian_fatalities',
 'civilian_injuries',
 'numberof_alarms',
 'primary_situation',
 'mutual_aid',
 'action_taken_primary',
 'action_taken_secondary',
 'action_taken_other',
 'detector_alerted_occupants',
 'property_use',
 'areaof_fire_origin',
 'ignition_cause',
 'ignition_factor_primary',
 'ignition_factor_secondary',
 'heat_source',
 'item_first_ignited',
 'human_factors_associatedwith_ignition',
 'structure_type',
 'structure_status',
 'floorof_fire_origin',
 'fire_spread',
 'no_flame_spread',
 'numberoffloorswithminimumdamage',
 'numberoffloorswithsignificantdamage',
 'numberoffloorswithheavydamage',
 'numberoffloorswithextremedamage',
 'detectors_present',
 'detector_type',
 'detector_operation',
 'detector_effectiveness',
 'detector_failure_reason',
 'automatic_extinguishing_system_present',
 'automatic_extinguishing_sytem_type',
 'automatic_extinguishing_sytem_perfomance',
 'automatic_extinguishing_sytem_failure_reason',
 'numberof_sprinkler_heads_operating',
 'supervisor_district',
 'neighborhood_district',
 'point',
 'data_as_of',
 'data_loaded_at']

In [8]:
df.columns = new_col

df.head()

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 733061 entries, 0 to 733060
Data columns (total 66 columns):
 #   Column                                        Non-Null Count   Dtype
---  ------                                        --------------   -----
 0   incident_number                               733061 non-null  int64
 1   exposure_number                               733061 non-null  int64
 2   i_d                                           733061 non-null  int64
 3   address                                       733061 non-null  str
 4   incident_date                                 733061 non-null  str
 5   call_number                                   733061 non-null  int64
 6   alarm_dt_tm                                   733061 non-null  str
 7   arrival_dt_tm                                 733061 non-null  str
 8   close_dt_tm                                   733061 non-null  str
 9   city                                          733061 non-null  str
 10  zipcode                                       733061 non-null  object
 11  battalion                                     733061 non-null  str
 12  station_area                                  733061 non-null  object
 13  box                                           733061 non-null  object
 14  suppression_units                             733061 non-null  object
 15  suppression_personnel                         733061 non-null  object
 16  e_m_s_units                                   733061 non-null  int64
 17  e_m_s_personnel                               733061 non-null  int64
 18  other_units                                   733061 non-null  object
 19  other_personnel                               733061 non-null  object
 20  first_unit_on_scene                           733061 non-null  str
 21  estimated_property_loss                       733061 non-null  str
 22  estimated_contents_loss                       733061 non-null  str
 23  fire_fatalities                               733061 non-null  int64
 24  fire_injuries                                 733061 non-null  int64
 25  civilian_fatalities                           733061 non-null  int64
 26  civilian_injuries                             733061 non-null  int64
 27  numberof_alarms                               733061 non-null  int64
 28  primary_situation                             733061 non-null  str
 29  mutual_aid                                    733061 non-null  str
 30  action_taken_primary                          733061 non-null  str
 31  action_taken_secondary                        733061 non-null  str
 32  action_taken_other                            733061 non-null  str
 33  detector_alerted_occupants                    733061 non-null  str
 34  property_use                                  733061 non-null  str
 35  areaof_fire_origin                            733061 non-null  str
 36  ignition_cause                                733061 non-null  str
 37  ignition_factor_primary                       733061 non-null  str
 38  ignition_factor_secondary                     733061 non-null  str
 39  heat_source                                   733061 non-null  str
 40  item_first_ignited                            733061 non-null  str
 41  human_factors_associatedwith_ignition         733061 non-null  str
 42  structure_type                                733061 non-null  str
 43  structure_status                              733061 non-null  str
 44  floorof_fire_origin                           733061 non-null  str
 45  fire_spread                                   733061 non-null  str
 46  no_flame_spread                               733061 non-null  str
 47  numberoffloorswithminimumdamage               733061 non-null  str
 48  numberoffloorswithsignificantdamage           733061 non-null  str
 49  numberoffloorswithheavydamage                 733061 non-null  str
 50  numberoffloorswithextremedamage               733061 non-null  str
 51  detectors_present                             733061 non-null  str
 52  detector_type                                 733061 non-null  str
 53  detector_operation                            733061 non-null  str
 54  detector_effectiveness                        733061 non-null  str
 55  detector_failure_reason                       733061 non-null  str
 56  automatic_extinguishing_system_present        733061 non-null  str
 57  automatic_extinguishing_sytem_type            733061 non-null  str
 58  automatic_extinguishing_sytem_perfomance      733061 non-null  str
 59  automatic_extinguishing_sytem_failure_reason  733061 non-null  str
 60  numberof_sprinkler_heads_operating            733061 non-null  str
 61  supervisor_district                           733061 non-null  str
 62  neighborhood_district                         733061 non-null  str
 63  point                                         733061 non-null  str
 64  data_as_of                                    733061 non-null  str
 65  data_loaded_at                                733061 non-null  str
dtypes: int64(11), object(7), str(48)
memory usage: 578.6+ MB

In [9]:
df["battalion"].unique(),df["battalion"].nunique()

(<ArrowStringArray>
 ['B01', 'B08', 'B06', 'B05', 'B09', 'B04', 'B02', 'B03', 'B10', 'B07', 'B99']
 Length: 11, dtype: str,
 11)

In [10]:
df["fire_injuries"] > 0

0         False
1         False
2         False
3         False
4         False
          ...
733056    False
733057    False
733058    False
733059    False
733060    False
Name: fire_injuries, Length: 733061, dtype: bool

In [11]:
df[(df["fire_injuries"] > 0)]

,incident_number,exposure_number,i_d,address,incident_date,call_number,alarm_dt_tm,arrival_dt_tm,close_dt_tm,city,...,automatic_extinguishing_system_present,automatic_extinguishing_sytem_type,automatic_extinguishing_sytem_perfomance,automatic_extinguishing_sytem_failure_reason,numberof_sprinkler_heads_operating,supervisor_district,neighborhood_district,point,data_as_of,data_loaded_at
874,8041622,0,80416220,3232 Pacific Av.,2008/05/15,81360145,2008/05/15 10:18:58 AM,2008/05/15 10:23:48 AM,2008/05/15 02:56:53 PM,SF,...,N -None Present,,,,0,2,Presidio,POINT (-122.4477435 37.79175063),2016/05/12 02:23:24 PM,2026/09/30 02:27:09 AM
2595,8048479,0,80484790,1800 Pacific Av.,2008/06/06,81580058,2008/06/06 06:28:03 AM,2008/06/06 06:31:02 AM,2008/06/06 10:38:52 AM,SF,...,N -None Present,,,,0,2,Pacific Heights,POINT (-122.424973 37.794664),2016/05/12 02:23:24 PM,2026/09/30 02:27:09 AM
3007,8050178,0,80501780,112 Clipper St.,2008/06/11,81630314,2008/06/11 03:48:20 PM,2008/06/11 03:51:19 PM,2008/06/11 04:50:49 PM,SF,...,,,,,0,8,Noe Valley,POINT (-122.42768236 37.74951272),2008/06/11 05:15:51 PM,2026/09/30 02:27:09 AM
6137,8061694,0,80616940,1527 La Salle Av.,2008/07/18,82000194,2008/07/18 02:14:49 PM,2008/07/18 02:24:32 PM,2008/07/18 07:19:37 PM,SF,...,N -None Present,,,,0,10,Bayview Hunters Point,POINT (-122.387589 37.735808),2016/05/12 02:23:24 PM,2026/09/30 02:27:09 AM
8403,8070085,0,80700850,42 Harbor Rd.,2008/08/15,82280342,2008/08/15 09:50:29 PM,2008/08/15 09:54:54 PM,2008/08/15 11:55:41 PM,SF,...,N -None Present,,,,0,10,Bayview Hunters Point,POINT (-122.37540027 37.73109299),2016/05/12 02:23:24 PM,2026/09/30 02:27:09 AM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
713467,13066434,0,130664340,373 HAIGHT ST,2013/07/15,131960055,2013/07/15 06:27:10 AM,2013/07/15 06:31:37 AM,2013/07/15 11:50:10 AM,SF,...,N -None Present,,,,0,5,Hayes Valley,POINT (-122.42825942 37.77217674),2016/05/12 02:23:24 PM,2026/09/30 02:27:09 AM
715547,13074664,0,130746640,AVENUE E / 9TH ST,2013/08/09,132210229,2013/08/09 04:01:00 PM,2013/08/09 04:03:44 PM,2013/08/09 09:26:05 PM,TI,...,N -None Present,,,,0,6,Treasure Island,POINT (-122.3715375 37.82256823),2016/05/12 02:23:24 PM,2026/09/30 02:27:09 AM
719161,13089072,0,130890720,3632 LYON ST,2013/09/20,132630141,2013/09/20 10:05:21 AM,2013/09/20 10:11:29 AM,2013/09/20 02:24:49 PM,SF,...,N -None Present,,,,0,2,Marina,POINT (-122.44791453 37.80458932),2016/05/12 02:23:24 PM,2026/09/30 02:27:09 AM
731343,14015152,0,140151520,339 JOOST AV,2014/02/13,140440418,2014/02/13 10:39:34 PM,2014/02/13 10:45:15 PM,2014/02/14 02:12:02 AM,SF,...,N -None Present,,,,0,7,West of Twin Peaks,POINT (-122.442933 37.732285),2014/02/14 08:01:14 AM,2026/09/30 02:27:09 AM
732834,14023691,0,140236910,1200 04TH STREET,2014/03/11,140700278,2014/03/11 04:55:27 PM,2014/03/11 05:00:23 PM,2014/03/12 07:22:43 AM,SAN FRANCISCO,...,N None Present,,,,,6,Mission Bay,POINT (-122.391283 37.771895),2016/05/12 02:23:23 PM,2026/09/30 02:27:09 AM

In [12]:
df[((df["fire_injuries"] > 0) | (df["civilian_injuries"] > 0)) & (df.battalion.isin(["B02", "B03"]))]["incident_number"]

4309       8055063
9627       8074589
12266      8084534
14176      8092030
29231     14039196
            ...
726183    13117071
728648    14003445
729640    14007758
732834    14023691
732854    14023834
Name: incident_number, Length: 111, dtype: int64

In [15]:
df[(df["city"].str.lstrip() == "") | df["city"].isna()]

,incident_number,exposure_number,i_d,address,incident_date,call_number,alarm_dt_tm,arrival_dt_tm,close_dt_tm,city,...,automatic_extinguishing_system_present,automatic_extinguishing_sytem_type,automatic_extinguishing_sytem_perfomance,automatic_extinguishing_sytem_failure_reason,numberof_sprinkler_heads_operating,supervisor_district,neighborhood_district,point,data_as_of,data_loaded_at
26986,14025411,0,140254110,3750 18TH STREET,2014/03/16,140750217,2014/03/16 02:14:48 PM,2014/03/16 02:18:21 PM,2014/03/16 02:32:52 PM,,...,,,,,,8,Castro/Upper Market,POINT (-122.427246 37.761395),2014/03/16 02:32:52 PM,2026/09/30 02:27:09 AM
27010,14025620,0,140256200,1600 HOLLOWAY AVENUE,2014/03/17,140760069,2014/03/17 07:27:16 AM,2014/03/17 07:34:30 AM,2014/03/17 07:51:31 AM,,...,,,,,,7,Lakeshore,POINT (-122.483602 37.722997),2014/03/17 07:51:31 AM,2026/09/30 02:27:09 AM
27013,14025637,0,140256370,1 THE EMBARCADERO SOU,2014/03/17,140760089,2014/03/17 08:53:04 AM,2014/03/17 08:59:10 AM,2014/03/17 09:22:17 AM,,...,,,,,,3,Financial District/South Beach,POINT (-122.393413 37.795204),2014/03/17 10:09:55 PM,2026/09/30 02:27:09 AM
27030,14025740,0,140257400,1 SF INTL AIRPORT,2014/03/17,140760217,2014/03/17 02:09:12 PM,2014/03/17 02:14:01 PM,2014/03/17 02:42:14 PM,,...,,,,,,,,POINT (-122.38416 37.616901),2014/03/18 06:12:13 AM,2026/09/30 02:27:09 AM
27038,14025797,0,140257970,401 HYDE STREET,2014/03/17,140760280,2014/03/17 05:25:59 PM,2014/03/17 05:26:00 PM,2014/03/17 05:41:29 PM,,...,,,,,,5,Tenderloin,POINT (-122.416175 37.784506),2014/03/17 05:41:29 PM,2026/09/30 02:27:09 AM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
732972,14024669,0,140246690,FREDERICK ST/STANYAN STREET,2014/03/14,140730215,2014/03/14 02:06:10 PM,2014/03/14 02:06:11 PM,2014/03/14 02:18:03 PM,,...,,,,,,5,Golden Gate Park,POINT (-122.452949 37.766374),2014/03/14 02:18:03 PM,2026/09/30 02:27:09 AM
732977,14024700,0,140247000,1001 POTRERO AV,2014/03/14,140730254,2014/03/14 03:27:25 PM,2014/03/14 03:27:25 PM,2014/03/14 04:25:37 PM,,...,,,,,,10,Mission,POINT (-122.406312 37.75541),2014/03/15 07:47:38 AM,2026/09/30 02:27:09 AM
733007,14024879,0,140248790,950 THE EMBARCADERO NOR,2014/03/15,140740017,2014/03/15 12:50:54 AM,2014/03/15 12:59:12 AM,2014/03/15 01:13:45 AM,,...,,,,,,3,Financial District/South Beach,POINT (-122.400603 37.80313),2014/03/15 01:13:45 AM,2026/09/30 02:27:09 AM
733022,14024958,0,140249580,1090 POINT LOBOS AV,2014/03/15,140740103,2014/03/15 09:06:34 AM,2014/03/15 09:17:37 AM,2014/03/15 10:53:37 AM,,...,,,,,,1,Outer Richmond,POINT (-122.513984 37.778495),2014/03/15 01:46:37 PM,2026/09/30 02:27:09 AM
733034,14025027,0,140250270,1111 GOUGH STREET,2014/03/15,140740200,2014/03/15 01:45:12 PM,2014/03/15 01:45:12 PM,2014/03/15 02:36:51 PM,,...,,,,,,2,Western Addition,POINT (-122.425412 37.784457),2014/03/15 02:36:51 PM,2026/09/30 02:27:09 AM

In [20]:
df["estimated_property_loss"] = df["estimated_property_loss"].str.replace("$","").str.replace(",","")
df['estimated_property_loss'] = pd.to_numeric(df['estimated_property_loss'], errors='coerce')
df[["incident_number","estimated_property_loss"]].sort_values(by="estimated_property_loss",ascending=False).head(10)

        incident_number  estimated_property_loss
609998          7006085              100000000.0
732834         14023691               40000000.0
278262         18032545               16000000.0
235113         20086100               13200000.0
235115         20086100               13200000.0
235114         20086100               13200000.0
235110         20086100               13200000.0
235116         20086100               13200000.0
235111         20086100               13200000.0
235112         20086100               13200000.0

In [23]:
df[df["incident_number"] == 5041531]

,incident_number,exposure_number,i_d,address,incident_date,call_number,alarm_dt_tm,arrival_dt_tm,close_dt_tm,city,...,automatic_extinguishing_system_present,automatic_extinguishing_sytem_type,automatic_extinguishing_sytem_perfomance,automatic_extinguishing_sytem_failure_reason,numberof_sprinkler_heads_operating,supervisor_district,neighborhood_district,point,data_as_of,data_loaded_at
169819,5041531,0,50415310,725 Geary St.,2005/06/05,51560019,2005/06/05 01:25:45 AM,2005/06/05 12:00:00 AM,2005/06/05 12:00:00 AM,SF,...,,,,,,5,Tenderloin,POINT (-122.41527511 37.78617521),2005/06/05 01:35:47 AM,2026/09/30 02:27:09 AM

#### Add ResponseMinutes = arrival minus alarm, in minutes. Flag rows where it is negative or over 120 minutes as suspicious.

In [30]:
df_new = df.copy()
df_new["ResponseMinutes"] = (pd.to_datetime(df_new["arrival_dt_tm"], format="%Y/%m/%d %I:%M:%S %p") - pd.to_datetime(df_new["alarm_dt_tm"], format="%Y/%m/%d %I:%M:%S %p")).dt.total_seconds() / 60
df_new["ResponseMinutes"] = df_new["ResponseMinutes"].fillna(0).astype(int)


df_new.loc[(df_new["ResponseMinutes"] < 0 )|  (df_new["ResponseMinutes"] > 120 ), ["incident_number","ResponseMinutes"]].head(10)

df_new.loc[(df_new["ResponseMinutes"] < 0 ), ["incident_number","ResponseMinutes"]].head(10)

        incident_number  ResponseMinutes
169819          5041531              -85
516236         19132632              -56
600305          6074461            -1008
601756          6079782             -926