In [2]:
import pandas as pd
import numpy as np

In [3]:
obj = pd.Series([4, -7, 5, 3])

obj

0    4
1   -7
2    5
3    3
dtype: int64

In [4]:
isinstance(obj.dtype,np.int64)

False

isinstance(obj.dtype, np.int64) is False because obj.dtype is not an integer; it is a metadata object describing the data.

Here is the breakdown of what is actually happening under the hood:

np.int64 is a scalar data type class (like Python's built-in int).

obj.dtype is an instance of numpy.dtype. It is a special container object that holds information about the data (byte order, data size, etc.), but it is not the data itself.

If you check the exact type of obj.dtype, you will see it is a dtype object, not an int64

In [5]:
isinstance(obj.dtype,np.dtype)

True

In [6]:
print(type(obj.dtype))

<class 'numpy.dtypes.Int64DType'>

If you were to check an actual element inside the Series, isinstance would return True, because the elements themselves are instances of np.int64:

In [7]:
isinstance(obj[0], np.int64)

True

In [8]:
obj.array

<NumpyExtensionArray>
[4, -7, 5, 3]
Length: 4, dtype: int64

In [9]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
obj = pd.Series([4, -7, 5, 3], index=['a', 'b', 'c', 'd'])
obj

a    4
b   -7
c    5
d    3
dtype: int64

In [11]:
obj.array

<NumpyExtensionArray>
[4, -7, 5, 3]
Length: 4, dtype: int64

In [12]:
obj.index

Index(['a', 'b', 'c', 'd'], dtype='str')

In [13]:
obj["b"]

np.int64(-7)

In [14]:
obj["d"] = 6

In [15]:
obj[['b','c','d']]

b   -7
c    5
d    6
dtype: int64

In [16]:
obj[obj > 0]

a    4
c    5
d    6
dtype: int64

Another way to think about a Series is as a fixed-length, ordered dictionary, as it is a
mapping of index values to data values

In [17]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

obj3 = pd.Series(sdata)

obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [18]:
"Ohio" in obj3

True

In [19]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

When you are only passing a dictionary, the index in the resulting Series will respect
the order of the keys according to the dictionary’s
method, which depends on
keys
the key insertion order. You can override this by passing an index with the dictionary
keys in the order you want them to appear in the resulting Series:

In [20]:
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [21]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [22]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

Series also has these as instance methods:

In [23]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [24]:
obj3,obj4

(Ohio      35000
 Texas     71000
 Oregon    16000
 Utah       5000
 dtype: int64,
 California        NaN
 Ohio          35000.0
 Oregon        16000.0
 Texas         71000.0
 dtype: float64)

In [25]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

Both the Series object itself and its index have a
attribute, which integrates with
name
other areas of pandas functionality:

In [26]:
obj4.name = "population"
obj4.index.name = "state"

print(obj4.name)

print(obj4.index.name)

population
state

In [27]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [28]:
obj

a    4
b   -7
c    5
d    6
dtype: int64

A Series’s index can be altered in place by assignment:

In [29]:
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]

obj

Bob      4
Steve   -7
Jeff     5
Ryan     6
dtype: int64

#### Dataframe

A DataFrame represents a rectangular table of data and contains an ordered, named
collection of columns, each of which can be a different value type (numeric, string,
Boolean, etc.). The DataFrame has both a row and column index; it can be thought of
as a dictionary of Series all sharing the same index.

In [30]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
"year": [2000, 2001, 2002, 2001, 2002, 2003],
"pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)

frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

as with Series,
and the columns are placed according to the order of the keys in
(which
data
depends on their insertion order in the dictionary)

For large DataFrames, the
method selects only the first five rows:
head

In [31]:
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

Similarly, tail returns the last five rows:

In [32]:
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

If you specify a sequence of columns, the DataFrame’s columns will be arranged in
that order

In [37]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop","debt"]) # Missing values are filled with NaN

frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [38]:
frame2["year"]

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [39]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [42]:
type(frame2["year"]), frame2["year"].name, frame2["year"].index, frame2["year"].values

(pandas.Series,
 'year',
 RangeIndex(start=0, stop=6, step=1),
 array([2000, 2001, 2002, 2001, 2002, 2003]))

works for any column name, but
frame2[column]
frame2.column
works only when the column name is a valid Python variable name
and does not conflict with any of the method names in DataFrame

Columns can be modified by assignment. For example, the empty
column could
debt
be assigned a scalar value or an array of values

In [43]:
frame2["debt"] = 16.5

frame2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [46]:
frame2["debt"] = np.arange(6.)

frame2

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

When you are assigning lists or arrays to a column, the value’s length must match the
length of the DataFrame


If you assign a Series, its labels will be realigned exactly to
the DataFrame’s index, inserting missing values in any index values not present:

In [47]:
val = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])

val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [49]:
frame2["debt"] = val

frame2

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

Index labels must match the DataFrame's index to assign a Series to a column

In [ ]:
val = pd.Series([-1.2, -1.5, -1.7], index=[0, "four", "five"]) # Index labels must match the DataFrame's index to assign a Series to a column

frame2["debt"] = val

frame2

   year   state  pop  debt
0  2000    Ohio  1.5  -1.2
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

Assigning a column that doesn’t exist will create a new column.

In [55]:

frame2["eastern"] = frame2.state == "Ohio"

frame2

   year   state  pop  debt  eastern
0  2000    Ohio  1.5  -1.2     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2   NaN    False

In [56]:
del frame2["eastern"]

frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='str')

In [57]:
frame2.values

array([[2000, 'Ohio', 1.5, -1.2],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [58]:
state = frame2["state"]

state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: str

In [60]:
state[0] = "New York"


state,frame2

(0    New York
 1        Ohio
 2        Ohio
 3      Nevada
 4      Nevada
 5      Nevada
 Name: state, dtype: str,
    year   state  pop  debt
 0  2000    Ohio  1.5  -1.2
 1  2001    Ohio  1.7   NaN
 2  2002    Ohio  3.6   NaN
 3  2001  Nevada  2.4   NaN
 4  2002  Nevada  2.9   NaN
 5  2003  Nevada  3.2   NaN)

## NOTE

Note on the future of Pandas: If you are using Pandas version 2.0 or newer, Pandas is transitioning to a new system called Copy-on-Write (CoW). When this is enabled, Pandas acts as a safeguard: it starts as a view to save memory, but the second you try to modify the series, it silently creates a copy in the background so your original DataFrame remains untouched.

In [ ]:
import pandas as pd

# Create a simple DataFrame
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})

# Extract column 'A' (This creates a VIEW)
my_series = df['A']

# Modify the first element of the extracted Series
my_series[0] = 99 

print(df)

#In pandas 2.0, this will create a copy in the background,
#In pandas 1.5, this will raise an error

#To force a copy, you can use the .copy() method:

my_series = df['A'].copy()

   A  B
0  1  4
1  2  5
2  3  6