In [655]:
import pandas as pd
import numpy as np

In [656]:
obj = pd.Series([4, -7, 5, 3])

obj

0    4
1   -7
2    5
3    3
dtype: int64

In [657]:
isinstance(obj.dtype,np.int64)

False

isinstance(obj.dtype, np.int64) is False because obj.dtype is not an integer; it is a metadata object describing the data.

Here is the breakdown of what is actually happening under the hood:

np.int64 is a scalar data type class (like Python's built-in int).

obj.dtype is an instance of numpy.dtype. It is a special container object that holds information about the data (byte order, data size, etc.), but it is not the data itself.

If you check the exact type of obj.dtype, you will see it is a dtype object, not an int64

In [658]:
isinstance(obj.dtype,np.dtype), obj.dtype.__class__

(True, numpy.dtypes.Int64DType)

In [659]:
issubclass(np.dtype, np.dtype)

True

In [660]:
print(type(obj.dtype))

<class 'numpy.dtypes.Int64DType'>

If you were to check an actual element inside the Series, isinstance would return True, because the elements themselves are instances of np.int64:

In [661]:
isinstance(obj[0], np.int64)

True

In [662]:
obj.array

<NumpyExtensionArray>
[4, -7, 5, 3]
Length: 4, dtype: int64

In [663]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [664]:
obj = pd.Series([4, -7, 5, 3], index=['a', 'b', 'c', 'd'])
obj

a    4
b   -7
c    5
d    3
dtype: int64

In [665]:
obj.array

<NumpyExtensionArray>
[4, -7, 5, 3]
Length: 4, dtype: int64

In [666]:
obj.index

Index(['a', 'b', 'c', 'd'], dtype='str')

In [667]:
obj["b"]

np.int64(-7)

In [668]:
obj["d"] = 6

In [669]:
obj[['b','c','d']]

b   -7
c    5
d    6
dtype: int64

In [670]:
obj[obj > 0]

a    4
c    5
d    6
dtype: int64

Another way to think about a Series is as a fixed-length, ordered dictionary, as it is a
mapping of index values to data values

In [671]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

obj3 = pd.Series(sdata)

obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [672]:
"Ohio" in obj3

True

In [673]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

When you are only passing a dictionary, the index in the resulting Series will respect
the order of the keys according to the dictionary’s
method, which depends on
keys
the key insertion order. You can override this by passing an index with the dictionary
keys in the order you want them to appear in the resulting Series:

In [674]:
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [675]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [676]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

Series also has these as instance methods:

In [677]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [678]:
obj3,obj4

(Ohio      35000
 Texas     71000
 Oregon    16000
 Utah       5000
 dtype: int64,
 California        NaN
 Ohio          35000.0
 Oregon        16000.0
 Texas         71000.0
 dtype: float64)

In [679]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

Both the Series object itself and its index have a
attribute, which integrates with
name
other areas of pandas functionality:

In [680]:
obj4.name = "population"
obj4.index.name = "state"

print(obj4.name)

print(obj4.index.name)

population
state

In [681]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [682]:
obj

a    4
b   -7
c    5
d    6
dtype: int64

A Series’s index can be altered in place by assignment:

In [683]:
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]

obj

Bob      4
Steve   -7
Jeff     5
Ryan     6
dtype: int64

#### Dataframe

A DataFrame represents a rectangular table of data and contains an ordered, named
collection of columns, each of which can be a different value type (numeric, string,
Boolean, etc.). The DataFrame has both a row and column index; it can be thought of
as a dictionary of Series all sharing the same index.

In [684]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
"year": [2000, 2001, 2002, 2001, 2002, 2003],
"pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)

frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

as with Series,
and the columns are placed according to the order of the keys in
(which
data
depends on their insertion order in the dictionary)

For large DataFrames, the
method selects only the first five rows:
head

In [685]:
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

Similarly, tail returns the last five rows:

In [686]:
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

If you specify a sequence of columns, the DataFrame’s columns will be arranged in
that order

In [687]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop","debt"]) # Missing values are filled with NaN

frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [688]:
frame2["year"]

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [689]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [690]:
type(frame2["year"]), frame2["year"].name, frame2["year"].index, frame2["year"].values

(pandas.Series,
 'year',
 RangeIndex(start=0, stop=6, step=1),
 array([2000, 2001, 2002, 2001, 2002, 2003]))

works for any column name, but
frame2[column]
frame2.column
works only when the column name is a valid Python variable name
and does not conflict with any of the method names in DataFrame

Columns can be modified by assignment. For example, the empty
column could
debt
be assigned a scalar value or an array of values

In [691]:
frame2["debt"] = 16.5

frame2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [692]:
frame2["debt"] = np.arange(6.)

frame2

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

When you are assigning lists or arrays to a column, the value’s length must match the
length of the DataFrame


If you assign a Series, its labels will be realigned exactly to
the DataFrame’s index, inserting missing values in any index values not present:

In [693]:
val = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])

val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [694]:
frame2["debt"] = val

frame2

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

Index labels must match the DataFrame's index to assign a Series to a column

In [695]:
val = pd.Series([-1.2, -1.5, -1.7], index=[0, "four", "five"]) # Index labels must match the DataFrame's index to assign a Series to a column

frame2["debt"] = val

frame2

   year   state  pop  debt
0  2000    Ohio  1.5  -1.2
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

Assigning a column that doesn’t exist will create a new column.

In [696]:

frame2["eastern"] = frame2.state == "Ohio"

frame2

   year   state  pop  debt  eastern
0  2000    Ohio  1.5  -1.2     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2   NaN    False

In [697]:
del frame2["eastern"]

frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='str')

In [698]:
frame2.drop(columns=["debt"])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [699]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='str')

In [700]:
frame2.values

array([[2000, 'Ohio', 1.5, -1.2],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [701]:
state = frame2["state"]

state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: str

In [702]:
state[0] = "New York"


state,frame2

(0    New York
 1        Ohio
 2        Ohio
 3      Nevada
 4      Nevada
 5      Nevada
 Name: state, dtype: str,
    year   state  pop  debt
 0  2000    Ohio  1.5  -1.2
 1  2001    Ohio  1.7   NaN
 2  2002    Ohio  3.6   NaN
 3  2001  Nevada  2.4   NaN
 4  2002  Nevada  2.9   NaN
 5  2003  Nevada  3.2   NaN)

## NOTE

Note on the future of Pandas: If you are using Pandas version 2.0 or newer, Pandas is transitioning to a new system called Copy-on-Write (CoW). When this is enabled, Pandas acts as a safeguard: it starts as a view to save memory, but the second you try to modify the series, it silently creates a copy in the background so your original DataFrame remains untouched.

In [703]:
import pandas as pd

# Create a simple DataFrame
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})

# Extract column 'A' (This creates a VIEW)
my_series = df['A']

# Modify the first element of the extracted Series
my_series[0] = 99 

print(df)

#In pandas 2.0, this will create a copy in the background,
#In pandas 1.5, this will raise an error

#To force a copy, you can use the .copy() method:

my_series = df['A'].copy()

   A  B
0  1  4
1  2  5
2  3  6

##### Nested dictionaries

If the nested dictionary is passed to the DataFrame, pandas will interpret the outer
dictionary keys as the columns, and the inner keys as the row indices:

In [704]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6}, "Nevada": {2001: 2.4, 2002: 2.9, "abc" : "2abc"}}
frame3 = pd.DataFrame(populations)
frame3

      Ohio Nevada
2000   1.5    NaN
2001   1.7    2.4
2002   3.6    2.9
abc    NaN   2abc

In [705]:
frame3.index

Index([2000, 2001, 2002, 'abc'], dtype='object')

The keys in the inner dictionaries are combined to form the index in the result. This
isn’t true if an explicit index is specified:

In [706]:
pd.DataFrame(populations, index=[2001, 2002, 2003])

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

You can transpose the DataFrame (swap rows and columns) with similar syntax to a
NumPy array:

In [707]:
frame3.T

       2000 2001 2002   abc
Ohio    1.5  1.7  3.6   NaN
Nevada  NaN  2.4  2.9  2abc

Note that transposing discards the column data types if the col
umns
do not all have the same data type, so transposing and then
transposing back may lose the previous type information. The col
umns
become arrays of pure Python objects in this case.

In [708]:
frame3["Nevada"]

2000     NaN
2001     2.4
2002     2.9
abc     2abc
Name: Nevada, dtype: object

In [709]:
frame3

      Ohio Nevada
2000   1.5    NaN
2001   1.7    2.4
2002   3.6    2.9
abc    NaN   2abc

Dictionaries of Series are treated in much the same way:

In [710]:
pdata = {"Ohio": frame3["Ohio"][:-1], "Nevada": frame3["Nevada"][:2]}
pd.DataFrame(pdata)

      Ohio Nevada
2000   1.5    NaN
2001   1.7    2.4
2002   3.6    NaN

If a DataFrame’s index and columns have their name attributes set, these will also be
displayed:

Unlike Series, DataFrame does not have a
attribute
name

In [711]:
frame3.index.name = "year"
frame3.columns.name = "state"
frame3

state  Ohio Nevada
year
2000    1.5    NaN
2001    1.7    2.4
2002    3.6    2.9
abc     NaN   2abc

DataFrame’s
to_numpy
method returns the data contained in the DataFrame as a two-dimensional ndarray

In [712]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9],
       [nan, '2abc']], dtype=object)

#### Index Objects

pandas’s Index objects are responsible for holding the axis labels (including a Data.
Frame’s column names) and other metadata (like the axis name or names).

In [713]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])

In [714]:
index  = obj.index

print(index)

print(index[1:])

Index(['a', 'b', 'c'], dtype='str')
Index(['b', 'c'], dtype='str')

Index objects are immutable

In [715]:
try:
    index[1] = "d" # This will raise an error
except Exception as e:
    print(e)

Index does not support mutable operations

Creating a index

In [716]:
labels = pd.Index(np.arange(3))
labels

Index([0, 1, 2], dtype='int64')

In [717]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
print(obj2)
print(obj2.index is labels)

0    1.5
1   -2.5
2    0.0
dtype: float64
True

In [718]:
frame3

state  Ohio Nevada
year
2000    1.5    NaN
2001    1.7    2.4
2002    3.6    2.9
abc     NaN   2abc

In [719]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='str', name='state')

In [720]:
frame3.index

Index([2000, 2001, 2002, 'abc'], dtype='object', name='year')

In [721]:
"Ohio" in frame3.columns,2000 in frame3.index

(True, True)

Unlike Python sets, a pandas Index can contain duplicate labels. Selections with duplicate labels will select all occurrences of that label.

In [722]:
index = pd.Index(["foo", "foo", "bar", "bar"])
index

Index(['foo', 'foo', 'bar', 'bar'], dtype='str')

In [723]:
index.is_unique, index.unique()

(False, Index(['foo', 'bar'], dtype='str'))

#### Reindexing

An important method on pandas objects is reindex, which means to create a new
object with the values rearranged to align with the new index.

In [724]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

Calling
on this Series rearranges the data according to the new index,
reindex
introducing missing values if any index values were not already present:

In [725]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

For ordered data like time series, you may want to do some interpolation or filling of
values when reindexing. The
option allows us to do this, using a method such
method
as ffill

In [726]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4]) 
obj3

0      blue
2    purple
4    yellow
dtype: str

In [727]:
obj3.reindex(range(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: str

With DataFrame,
can alter the (row) index, columns, or both. When passed
reindex
only a sequence, it reindexes the rows in the result

In [728]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
index=["a", "c", "d"],
columns=["Ohio", "Texas", "California"])
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [729]:
frame2 = frame.reindex(["a", "b", "c", "d"])
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

The columns can be reindexed with the columns keyword

In [730]:
states = ["Texas", "Utah", "California"]
frame3 = frame.reindex(columns= states)
frame3 #Because "Ohio" was not in states, the data for that column is dropped from the result

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

Another way to reindex a particular axis is to pass the new axis labels as a positional
argument and then specify the axis to reindex with the
keyword:
axis

In [731]:
frame.reindex(states, axis=1)

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [732]:
frame.reindex(states, axis=0)

            Ohio  Texas  California
Texas        NaN    NaN         NaN
Utah         NaN    NaN         NaN
California   NaN    NaN         NaN

In [733]:
frame.reindex(states, axis="rows")

            Ohio  Texas  California
Texas        NaN    NaN         NaN
Utah         NaN    NaN         NaN
California   NaN    NaN         NaN

In [734]:
frame.reindex(states, axis="index") # same as rows and this is default

            Ohio  Texas  California
Texas        NaN    NaN         NaN
Utah         NaN    NaN         NaN
California   NaN    NaN         NaN

In [735]:
frame.reindex(states, axis="columns")

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [736]:
frame.loc[["a", "d", "c"], ["California", "Texas"]] # reindexing with loc

   California  Texas
a           2      1
d           8      7
c           5      4

#### Dropping Entries from an axis

In [737]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [738]:
new_obj = obj.drop("c")
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [739]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [740]:
obj.drop(["d", "c"])

a    0.0
b    1.0
e    4.0
dtype: float64

With DataFrame, index values can be deleted from either axis. To illustrate this, we
first create an example DataFrame

In [741]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=["Ohio", "Colorado", "Utah", "New York"],
columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [742]:
data.drop(index=["Colorado", "Ohio"])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

You can also drop values from the columns by passing axis=1 (which is like NumPy)
or axis="columns":

In [743]:
data.drop("two", axis=1)

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [744]:
data.drop(columns=["two", "four"])

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [745]:
obj = pd.Series(np.arange(5), index=["a", "b", "c", "d", "e"])

obj

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [746]:
obj['b']

np.int64(1)

In [747]:
try:
    obj[1]
except Exception as e:
    print("This doesn't work in pandas 2.0")

This doesn't work in pandas 2.0

In [748]:
obj[2:4]

c    2
d    3
dtype: int64

In [749]:
obj[["b", "a", "d"]]

b    1
a    0
d    3
dtype: int64

In [750]:
obj[obj < 2]

a    0
b    1
dtype: int64

In [751]:
obj.loc[["b", "a", "d"]]

b    1
a    0
d    3
dtype: int64

The reason to prefer
is because of the different treatment of integers when
loc
indexing with []. Regular []-based indexing will treat integers as labels if the index
contains integers, so the behavior differs depending on the data type of the index. 


Since
operator indexes exclusively with labels, there is also an
operator
loc
iloc
that indexes exclusively with integers to work consistently whether or not the index
contains integers:

You can also slice with labels, but it works differently from normal
Python slicing in that the endpoint is inclusive:

In [752]:
obj.loc["b":"c"]

b    1
c    2
dtype: int64

Assigning values using these methods modifies the corresponding section of the
Series:

In [753]:
obj.loc["b":"c"] = 5

obj

a    0
b    5
c    5
d    3
e    4
dtype: int64

In [754]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=["Ohio", "Colorado", "Utah", "New York"],
columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

Indexing into a DataFrame retrieves one or more columns either with a single value
or sequence

In [755]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [756]:
data.index

Index(['Ohio', 'Colorado', 'Utah', 'New York'], dtype='str')

In [757]:
data[["three", "one"]]

          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

The row selection syntax
is provided as a convenience. Passing a single
data[:2]
element or a list to the
operator selects columns.
[]

In [758]:
data[:2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [759]:
data[-1:]

          one  two  three  four
New York   12   13     14    15

In [760]:
data.iloc[[2, 1]]

          one  two  three  four
Utah        8    9     10    11
Colorado    4    5      6     7

In [761]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [762]:
type(data.iloc[2, [3, 0, 1]])

pandas.Series

In [763]:
data.iloc[[1, 2], [3, 0, 1]]

          four  one  two
Colorado     7    4    5
Utah        11    8    9

In [764]:
data.iloc[[1, 2], [3, 0, 1]]

          four  one  two
Colorado     7    4    5
Utah        11    8    9

In [765]:
data.iloc[:, :3]

          one  two  three
Ohio        0    1      2
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

Both indexing functions work with slices in addition to single labels or lists of labels:

In [766]:
data.loc[: "Ohio", "one"]

Ohio    0
Name: one, dtype: int64

In [767]:
data.loc[: ,["one"]]

          one
Ohio        0
Colorado    4
Utah        8
New York   12

Boolean arrays can be used with
but not iloc:
loc

In [768]:
data.loc[data.three >= 2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [769]:
try:
    data.iloc[data.three >= 2]
except Exception as e:
    print(e)

iLocation based boolean indexing cannot use an indexable as a mask

In [770]:
data.loc[["Ohio","Utah"],["one","two"]]

      one  two
Ohio    0    1
Utah    8    9

In [771]:
ser = pd.Series(np.arange(3.))

ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [772]:
try:
    ser[-1]
except Exception as e:
    print(e)

-1

In [773]:
ser2 = pd.Series(np.arange(3.), index=["a", "b", "c"])

ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [774]:
try:
    print(ser2[-1])
except Exception as e:
    print(e)

-1

In [775]:
ser.iloc[-1],ser2.iloc[-1]

(np.float64(2.0), np.float64(2.0))

### slicing with integers is always integer oriented

In [776]:
ser[:2]

0    0.0
1    1.0
dtype: float64

In [777]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [778]:
ser[:1] = 2
ser

0    2.0
1    1.0
2    2.0
dtype: float64

These indexing attributes can also be used to modify
DataFrame objects in place, but doing so requires some care.

In [779]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [780]:
data.loc[["Ohio"],["one"]]

      one
Ohio    0

In [781]:
data.loc["Ohio","one"]

np.int64(0)

In [782]:
data.loc[:,["one"]]

          one
Ohio        0
Colorado    4
Utah        8
New York   12

In [783]:
data.iloc[2] = 5
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        5    5      5     5
New York   12   13     14    15

In [784]:
data["four"] > 5

Ohio        False
Colorado     True
Utah        False
New York     True
Name: four, dtype: bool

In [785]:
data.loc[data["four"] > 5] = 3
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [786]:
data.index, data.columns, data.values

(Index(['Ohio', 'Colorado', 'Utah', 'New York'], dtype='str'),
 Index(['one', 'two', 'three', 'four'], dtype='str'),
 array([[0, 1, 2, 3],
        [3, 3, 3, 3],
        [5, 5, 5, 5],
        [3, 3, 3, 3]]))

In [787]:
data.four

Ohio        3
Colorado    3
Utah        5
New York    3
Name: four, dtype: int64

In [788]:
data.loc[data.three == 5]["three"] = 6

/var/folders/ft/l9mh6cgx0jj0zxzptbybbspr0000gn/T/ipykernel_6449/867481848.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  data.loc[data.three == 5]["three"] = 6

Depending on the data contents, this may print a special SettingWithCopyWarning,
which warns you that you are trying to modify a temporary value (the nonempty result of
5]) instead of the original DataFrame data, which might be what you were intending.

In [789]:
data.loc[data.three == 5, "three"] = 6
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    3    3      3     3
Utah        5    5      6     5
New York    3    3      3     3

In [794]:
s1 = pd.Series([1,2,3,4,5], index=["a","b","c","d","e"])
s2 = pd.Series([1,2,3,4,5], index=["a","b","c","i","j"])
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [795]:
s2

a    1
b    2
c    3
i    4
j    5
dtype: int64

In [796]:
s1+s2

a    2.0
b    4.0
c    6.0
d    NaN
e    NaN
i    NaN
j    NaN
dtype: float64

The internal data alignment introduces missing values in the label locations that don’t
overlap. Missing values will then propagate in further arithmetic computations.

In the case of DataFrame, alignment is performed on both rows and columns:

In [802]:
df1 = pd.DataFrame(np.arange(12).reshape((3,4)), columns=list("abcd"), index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12,24).reshape((4,3)), columns=list("cde"), index=["Utah", "Ohio", "Texas", "Oregon"])

df1

          a  b   c   d
Ohio      0  1   2   3
Texas     4  5   6   7
Colorado  8  9  10  11

In [803]:
df2

         c   d   e
Utah    12  13  14
Ohio    15  16  17
Texas   18  19  20
Oregon  21  22  23

Adding these returns a DataFrame with index and columns that are the unions of the
ones in each DataFrame:

In [804]:
df1+df2

           a   b     c     d   e
Colorado NaN NaN   NaN   NaN NaN
Ohio     NaN NaN  17.0  19.0 NaN
Oregon   NaN NaN   NaN   NaN NaN
Texas    NaN NaN  24.0  26.0 NaN
Utah     NaN NaN   NaN   NaN NaN

Since the "a"
 and "b"
columns are not found in both DataFrame objects, they appear

as missing in the result. The same holds for the rows with labels that are not common
to both objects.


If you add DataFrame objects with no column or row labels in common, the result
will contain all nulls:

#### In arithmetic operations between differently indexed objects, you might want to fill with a special value, like 0, when an axis label is found in one object but not the other.

In [805]:
df1 = pd.DataFrame(np.arange(12).reshape((3,4)), columns=list("abcd"))
df2 = pd.DataFrame(np.arange(20).reshape((4,5)), columns=list("abcde"))
df1

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [806]:
df2

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [808]:
df2.loc[1,"b"] = np.nan
df2

    a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [807]:
df1+df2

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [810]:
df1.add(df2)

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [811]:
df1.radd(df2)

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

Using the
method on df1, I pass
and an argument to
value, which
add
df2
fill_
substitutes the passed value for any missing values in the operation:

In [809]:
df1.add(df2, fill_value=0)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [812]:
1/df1

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [813]:
df1.rdiv(1)

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

Relatedly, when reindexing a Series or DataFrame, you can also specify a different fill
value:

In [814]:
df1.reindex(columns = df2.columns, fill_value = 0)

   a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

### Broadcasting in Pandas

In [815]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)), columns=list("bde"), index=["Utah", "Ohio", "Texas", "Oregon"])
frame

        b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [817]:
series = frame.iloc[0]
series

b    0
d    1
e    2
Name: Utah, dtype: int64

By default, arithmetic between DataFrame and Series matches the index of the Series
on the columns of the DataFrame, broadcasting down the rows:

In [818]:
frame - series

        b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [819]:
series2 = pd.Series(range(4), index=["a", "b", "c", "d"])
series2

a    0
b    1
c    2
d    3
dtype: int64

If an index value is not found in either the DataFrame’s columns or the Series’s index,
the objects will be reindexed to form the union:

In [820]:
frame - series2

         a    b   c    d   e
Utah   NaN -1.0 NaN -2.0 NaN
Ohio   NaN  2.0 NaN  1.0 NaN
Texas  NaN  5.0 NaN  4.0 NaN
Oregon NaN  8.0 NaN  7.0 NaN

If you want to instead broadcast over the columns, matching on the rows, you have to
use one of the arithmetic methods and specify to match over the index. For example:

In [822]:
frame

        b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [ ]:
series3 = frame["d"]
series3

Utah       1
Ohio       4
Texas      7
Oregon    10
Name: d, dtype: int64

In [824]:
frame - series3

        Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

In [823]:
frame.sub(series3, axis="index")

        b  d  e
Utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1

The axis that you pass is the axis to match on. In this case we mean to match on the
DataFrame’s row index (
index") and broadcast across the columns
axis="

#### NumPy ufuncs (element-wise array methods) also work with pandas objects:

In [825]:
frame = pd.DataFrame(np.random.randn(4,3), columns=list("bde"), index=["Utah", "Ohio", "Texas", "Oregon"])
frame

               b         d         e
Utah    0.840898  0.010599  0.659061
Ohio   -2.287969  0.858181  0.710352
Texas   1.401133 -1.305203 -0.302737
Oregon  0.318545 -1.454890 -0.881250

In [826]:
np.abs(frame)

               b         d         e
Utah    0.840898  0.010599  0.659061
Ohio    2.287969  0.858181  0.710352
Texas   1.401133  1.305203  0.302737
Oregon  0.318545  1.454890  0.881250

Another frequent operation is applying a function on one-dimensional arrays to each
column or row. DataFrame’s
method does exactly this:
apply

Here the function f, which computes the difference between the maximum and
minimum of a Series, is invoked once on each column in frame. The result is a Series
having the columns of
as its index.
frame

In [827]:
#### Applying functions to pandas objects
f = lambda x: x.max() - x.min()
frame.apply(f)

b    3.689101
d    2.313071
e    1.591602
dtype: float64

If you pass
to apply, the function will be invoked once per row
axis="columns"
instead. A helpful way to think about this is as “apply across the columns”:

In [828]:
frame.apply(f, axis="columns")

Utah      0.830299
Ohio      3.146149
Texas     2.706336
Oregon    1.773435
dtype: float64

Many of the most common array statistics (like
and mean) are DataFrame meth
sum
ods,
so using
is not necessary.
apply. The function passed to
need not return a scalar value; it can also return a Series
apply
with multiple values:

In [829]:
def f(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])
frame.apply(f)

            b         d         e
min -2.287969 -1.454890 -0.881250
max  1.401133  0.858181  0.710352

Element-wise Python functions can be used, too. Suppose you wanted to compute
a formatted string from each floating-point value in frame. You can do this with
applymap

In [831]:
def format(x):
    return f"{x:.2f}"
frame.map(format)

            b      d      e
Utah     0.84   0.01   0.66
Ohio    -2.29   0.86   0.71
Texas    1.40  -1.31  -0.30
Oregon   0.32  -1.45  -0.88

#### Difference between map() and apply()

While both methods are used to transform data in pandas, the core difference comes down to what the method is looking at (a single element vs. an entire row/column) and what kind of input it accepts (functions vs. dictionaries).

Here is the breakdown of how they differ.

1. map(): The Element-by-Element Transformer
map() operates on individual elements one at a time. It is primarily used for substituting each value in a Series (or DataFrame) with another value.

What it accepts: Functions, dictionaries, or other Series. (This makes it incredibly powerful for mapping categories).

How it works: It looks at a single cell, transforms it, and moves to the next cell.

Example: Using a dictionary to map values

In [832]:
import pandas as pd

s = pd.Series(['cat', 'dog', 'cat'])

# Map accepts a dictionary for quick substitution
s.map({'cat': 'kitten', 'dog': 'puppy'})

0    kitten
1     puppy
2    kitten
dtype: str

Example: Element-wise DataFrame math

In [833]:
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})

# Multiplies every individual cell by 10
df.map(lambda x: x * 10)

    A   B
0  10  30
1  20  40

2. apply(): The Row/Column Processor
apply() operates on entire rows or columns at a time when used on a DataFrame. Instead of passing a single number to your function, it passes an entire pandas Series (the whole row or the whole column).

What it accepts: Functions only.

How it works on a DataFrame: It looks at a whole axis (row or column), performs an operation on that array of data, and moves to the next axis.

Example: Applying a function across columns

In [834]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [10, 20, 30]})

# sum() takes an entire list/array of numbers. 
# apply() passes column 'A', then column 'B' to the sum() function.
df.apply(sum) 

# Output:
# A     6
# B    60

A     6
B    60
dtype: int64

Example: Applying across rows (axis=1)

In [835]:
# Passes row 0, then row 1, then row 2 to the max() function
df.apply(max, axis=1)

0    10
1    20
2    30
dtype: int64

(Note: If you use apply() on a single 1D Series, it behaves exactly like a function-based map(), acting element-by-element).

#### Sorting

In [836]:
obj = pd.Series(np.arange(4), index=["d", "a", "c", "b"])
obj

d    0
a    1
c    2
b    3
dtype: int64

In [837]:
obj.sort_index()

a    1
b    3
c    2
d    0
dtype: int64

In [838]:
obj.sort_values()

d    0
a    1
c    2
b    3
dtype: int64

#### With a DataFrame, you can sort by either axis

In [839]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), index=["three", "one"], columns=["d", "a", "b", "c"])

frame

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [840]:
frame.sort_index()

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [845]:
frame.sort_index(axis=1)

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [847]:
frame.sort_index(axis="columns", ascending=False)

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

Any missing values are sorted to the end of the Series by default:

In [848]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

Missing values can be sorted to the start instead by using the
option:
na_position

In [849]:
obj.sort_values(na_position="first")

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

When sorting a DataFrame, you can use the data in one or more columns as the sort
keys. To do so, pass one or more column names to
_values:
sort

In [856]:
frame = pd.DataFrame({"b":[4,3,2,1], "a":[0,1,0,1]})

frame

   b  a
0  4  0
1  3  1
2  2  0
3  1  1

In [857]:
frame.sort_values(by="a")

   b  a
0  4  0
2  2  0
1  3  1
3  1  1

In [858]:
frame.sort_values(by=["a", "b"])

   b  a
2  2  0
0  4  0
3  1  1
1  3  1

#### Ranking

Ranking assigns ranks from one through the number of valid data points in an array,
starting from the lowest value. The
methods for Series and DataFrame are the
rank
place to look; by default,
breaks ties by assigning each group the mean rank
rank

In [860]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [861]:

obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

Ranks can also be assigned according to the order in which they’re observed in the
data:

In [863]:
obj.rank(method="first") #Instead of the mean rank, this assigns the rank of the first occurrence of the value.

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [864]:
obj.rank(ascending=False) #Ranks are assigned in descending order.

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

DataFrame can compute ranks over the rows or the columns:

In [865]:
frame = pd.DataFrame({"a": [10, 7, 4, 3, 2], "b": [20, 17, 14, 13, 12], "c": [30, 27, 24, 23, 22]})

frame

    a   b   c
0  10  20  30
1   7  17  27
2   4  14  24
3   3  13  23
4   2  12  22

In [866]:
frame.rank(axis=1)

     a    b    c
0  1.0  2.0  3.0
1  1.0  2.0  3.0
2  1.0  2.0  3.0
3  1.0  2.0  3.0
4  1.0  2.0  3.0

In [867]:
frame.rank(axis="columns")

     a    b    c
0  1.0  2.0  3.0
1  1.0  2.0  3.0
2  1.0  2.0  3.0
3  1.0  2.0  3.0
4  1.0  2.0  3.0

In [868]:
frame.rank(axis="rows")

     a    b    c
0  5.0  5.0  5.0
1  4.0  4.0  4.0
2  3.0  3.0  3.0
3  2.0  2.0  2.0
4  1.0  1.0  1.0

"average" : Default: assign the average rank to each entry in the equal group

"min" :  Use the minimum rank for the whole group

"max" : Use the maximum rank for the whole group

"first" : Assign ranks in the order the values appear in the data

"dense" : Like method="min", but ranks always increase by 1 between groups rather than the number of equal
elements in a group

### Axis Indexes with Duplicate Labels

While many pandas functions (like reindex) require that the labels be
unique, it’s not mandatory. Let’s consider a small Series with duplicate indices:

In [869]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])

obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [870]:
obj.index.is_unique

False

Data selection is one of the main things that behaves differently with duplicates.
Indexing a label with multiple entries returns a Series, while single entries return a
scalar value:

In [ ]:
obj["a"]

a    0
a    1
dtype: int64

In [873]:
obj["c"]

np.int64(4)

In [872]:
type(obj["a"])

pandas.Series

This can make your code more complicated, as the output type from indexing can
vary based on whether or not a label is repeated.

The same logic extends to indexing rows (or columns) in a DataFrame:

In [874]:
df = pd.DataFrame(np.arange(16).reshape((4,4)), index=["a", "a", "b", "c"])

df

    0   1   2   3
a   0   1   2   3
a   4   5   6   7
b   8   9  10  11
c  12  13  14  15

In [875]:
df.loc["a"]

   0  1  2  3
a  0  1  2  3
a  4  5  6  7

In [876]:
df.loc["c"]

0    12
1    13
2    14
3    15
Name: c, dtype: int64

Most of these fall into the category of reductions or summary statistics, methods
that extract a single value (like the sum or mean) from a Series, or a Series of values
from the rows or columns of a DataFrame. Compared with the similar methods
found on NumPy arrays, they have built-in handling for missing data. Consider a
small DataFrame

In [877]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index=["a", "b", "c", "d"], columns=["one", "two"])

df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

Calling DataFrame’s
method returns a Series containing column sums:
sum

In [878]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [879]:
df.sum(axis=1) # or axis="columns"

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

When an entire row or column contains all NA values, the sum is 0, whereas if any
value is not NA, then the result is NA. This can be disabled with the
option, in
skipna
which case any NA value in a row or column names the corresponding result NA:

In [880]:
df.sum(skipna=False)

one   NaN
two   NaN
dtype: float64

In [881]:
df.sum(axis="columns", skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

Some aggregations, like mean, require at least one non-NA value to yield a value
result, so here we have:

In [882]:
df.mean(axis="columns")

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [883]:
df.describe()

            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

On nonnumeric data,
produces alternative summary statistics:
describe

In [884]:
obj = pd.Series(["a", "a", "b", "c"] * 4)

obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: str

In [885]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

#### Correlation and Covariance

Some summary statistics, like correlation and covariance, are computed from pairs
of arguments. Let’s consider some DataFrames of stock prices and volumes originally
obtained from Yahoo! Finance

In [891]:
import sys

# 1. Map the general index module
sys.modules['pandas.indexes'] = sys.modules['pandas.core.indexes']

# 2. Map the time-series index module
sys.modules['pandas.tseries.index'] = sys.modules['pandas.core.indexes.datetimes']

price = pd.read_pickle("examples/yahoo_price.pkl")

price

                  AAPL        GOOG         IBM       MSFT
Date
2010-01-04   27.990226  313.062468  113.304536  25.884104
2010-01-05   28.038618  311.683844  111.935822  25.892466
2010-01-06   27.592626  303.826685  111.208683  25.733566
2010-01-07   27.541619  296.753749  110.823732  25.465944
2010-01-08   27.724725  300.709808  111.935822  25.641571
...                ...         ...         ...        ...
2016-10-17  117.550003  779.960022  154.770004  57.220001
2016-10-18  117.470001  795.260010  150.720001  57.660000
2016-10-19  117.120003  801.500000  151.259995  57.529999
2016-10-20  117.059998  796.969971  151.520004  57.250000
2016-10-21  116.599998  799.369995  149.630005  59.660000

[1714 rows x 4 columns]

In [892]:
volume = pd.read_pickle("examples/yahoo_volume.pkl")

volume

                 AAPL      GOOG       IBM      MSFT
Date
2010-01-04  123432400   3927000   6155300  38409100
2010-01-05  150476200   6031900   6841400  49749600
2010-01-06  138040000   7987100   5605300  58182400
2010-01-07  119282800  12876600   5840600  50559700
2010-01-08  111902700   9483900   4197200  51197400
...               ...       ...       ...       ...
2016-10-17   23624900   1089500   5890400  23830000
2016-10-18   24553500   1995600  12770600  19149500
2016-10-19   20034600    116600   4632900  22878400
2016-10-20   24125800   1734200   4023100  49455600
2016-10-21   22384800   1260500   4401900  79974200

[1714 rows x 4 columns]

In [893]:
returns = price.pct_change()
returns

                AAPL      GOOG       IBM      MSFT
Date
2010-01-04       NaN       NaN       NaN       NaN
2010-01-05  0.001729 -0.004404 -0.012080  0.000323
2010-01-06 -0.015906 -0.025209 -0.006496 -0.006137
2010-01-07 -0.001849 -0.023280 -0.003462 -0.010400
2010-01-08  0.006648  0.013331  0.010035  0.006897
...              ...       ...       ...       ...
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

[1714 rows x 4 columns]

The corr method of Series computes the correlation of the overlapping, non-NA,
aligned-by-index values in two Series. Relatedly,cov  computes the covariance:

In [894]:
returns["MSFT"].corr(returns["IBM"])

np.float64(0.49976361144151166)

In [896]:
returns["IBM"].corr(returns["IBM"])

np.float64(1.0)

In [895]:
returns["MSFT"].cov(returns["IBM"])

np.float64(8.870655479703549e-05)

DataFrame’s
and
methods, on the other hand, return a full correlation or
corr
cov
covariance matrix as a DataFrame, respectively:

#### Both cov() (covariance) and corr() (correlation) are used to measure the relationship between two sets of numbers. They tell you whether two variables tend to move in the same direction, in opposite directions, or if they have no relationship at all.

Covariance (cov) tells you the direction of the relationship (positive or negative). However, the number it outputs is unbounded and depends entirely on the units of your data (e.g., dollars vs. millions of dollars). This makes it hard to compare across different datasets.

Correlation (corr) is exactly like covariance, but it is scaled. It always outputs a number strictly between -1.0 and 1.0, regardless of the units. This makes it the standard way to measure both the direction and the strength of a relationship.

While corr() is used to find the relationship between all columns inside a single DataFrame, corrwith() is used to find the relationship between a DataFrame and something else (like a separate Series or another DataFrame).

Think of it like a sports tournament:

corr() is a round-robin tournament: Every column plays against every other column inside the same DataFrame. It outputs a large, square grid (matrix).

corrwith() is a team match: Every column in your DataFrame plays against a specific external opponent. It outputs a simple, 1D list of scores.

Here are the two main ways you will use it.

Scenario 1: Comparing a DataFrame against a single Series
This is the most common use case in data science and machine learning. You have a DataFrame full of features (like test scores) and a single target Series (like hours studied). You want to see how each feature correlates to the target.

In [897]:
import pandas as pd

# Our features DataFrame
df = pd.DataFrame({
    'Math_Score': [70, 80, 90, 100],
    'Science_Score': [75, 85, 95, 100],
    'Art_Score': [100, 90, 80, 70]
})

print(df)
# Our target Series
study_hours = pd.Series([2, 4, 6, 8])
print(study_hours)
# Calculate correlation of every column in 'df' against 'study_hours'
result = df.corrwith(study_hours)

print(result)

   Math_Score  Science_Score  Art_Score
0          70             75        100
1          80             85         90
2          90             95         80
3         100            100         70
0    2
1    4
2    6
3    8
dtype: int64
Math_Score       1.000000
Science_Score    0.989778
Art_Score       -1.000000
dtype: float64

Instead of a giant matrix, you get a clean summary: studying has a perfect positive correlation with Math, a strong positive correlation with Science, and a perfect negative correlation with Art.

Scenario 2: Comparing a DataFrame against another DataFrame
If you pass another DataFrame into corrwith(), pandas will match up columns with the same name and calculate the correlation between them. (It does not cross-compare every column to every other column).

This is highly useful if you have two datasets representing the same metrics taken at different times, or predicted values vs. actual values.

In [898]:
# DataFrame 1: Actual Sales
actual = pd.DataFrame({
    'Apples': [10, 20, 30, 40],
    'Oranges': [5, 10, 15, 20]
})

# DataFrame 2: Predicted Sales
predicted = pd.DataFrame({
    'Apples': [12, 18, 33, 38],   # Close to actual
    'Oranges': [20, 15, 10, 5]    # Completely opposite of actual
})

print(actual)
print("--------------------------------")
print(predicted)
# Compare column by column
result = actual.corrwith(predicted)

print(result)

   Apples  Oranges
0      10        5
1      20       10
2      30       15
3      40       20
--------------------------------
   Apples  Oranges
0      12       20
1      18       15
2      33       10
3      38        5
Apples     0.97949
Oranges   -1.00000
dtype: float64

Here, pandas compared actual['Apples'] with predicted['Apples'], and then actual['Oranges'] with predicted['Oranges'].

Key Parameters to Know
You can customize corrwith() exactly like you can with corr():

method='spearman' (or 'kendall'): Changes the math from the default Pearson calculation to one that handles non-linear relationships or rankings better.

axis=1: Flips the operation to compare rows instead of columns.


Row labels (the index) are always matched first before any math happens.

In pandas, this is called automatic index alignment. Before corrwith() calculates the correlation, it lines up the data based on their row index labels.

If the row labels don't match perfectly, pandas will pair them up where they do match, and put NaN everywhere else. Then, because corrwith() uses pairwise deletion (as we discussed previously), it effectively only calculates the correlation using the rows that share the exact same index label.

Here is an example to show this in action:

In [899]:
import pandas as pd

# DataFrame with index A, B, C
df = pd.DataFrame({
    'Math_Score': [10, 20, 30]
}, index=['A', 'B', 'C'])

# Series with index B, C, D
study_hours = pd.Series([15, 25, 35], index=['B', 'C', 'D'])

# Calculate correlation
print(df.corrwith(study_hours))

Math_Score    1.0
dtype: float64

#### Unique, Value Counts and Membership

In [900]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])

uniques = obj.unique()

uniques

<ArrowStringArray>
['c', 'a', 'd', 'b']
Length: 4, dtype: str

The unique values are not necessarily returned in the order in which they first
appear, and not in sorted order, but they could be sorted after the fact if needed

uniques.sort()

In [901]:
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

The Series is sorted by value in descending order as a convenience.
is
value_counts
also available as a top-level pandas method that can be used with NumPy arrays or
other Python sequences: