In [325]:
import pandas as pd
import numpy as np

In [326]:
obj = pd.Series([4, -7, 5, 3])

obj

0    4
1   -7
2    5
3    3
dtype: int64

In [327]:
isinstance(obj.dtype,np.int64)

False

isinstance(obj.dtype, np.int64) is False because obj.dtype is not an integer; it is a metadata object describing the data.

Here is the breakdown of what is actually happening under the hood:

np.int64 is a scalar data type class (like Python's built-in int).

obj.dtype is an instance of numpy.dtype. It is a special container object that holds information about the data (byte order, data size, etc.), but it is not the data itself.

If you check the exact type of obj.dtype, you will see it is a dtype object, not an int64

In [328]:
isinstance(obj.dtype,np.dtype), obj.dtype.__class__

(True, numpy.dtypes.Int64DType)

In [329]:
issubclass(np.dtype, np.dtype)

True

In [330]:
print(type(obj.dtype))

<class 'numpy.dtypes.Int64DType'>

If you were to check an actual element inside the Series, isinstance would return True, because the elements themselves are instances of np.int64:

In [331]:
isinstance(obj[0], np.int64)

True

In [332]:
obj.array

<NumpyExtensionArray>
[4, -7, 5, 3]
Length: 4, dtype: int64

In [333]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [334]:
obj = pd.Series([4, -7, 5, 3], index=['a', 'b', 'c', 'd'])
obj

a    4
b   -7
c    5
d    3
dtype: int64

In [335]:
obj.array

<NumpyExtensionArray>
[4, -7, 5, 3]
Length: 4, dtype: int64

In [336]:
obj.index

Index(['a', 'b', 'c', 'd'], dtype='str')

In [337]:
obj["b"]

np.int64(-7)

In [338]:
obj["d"] = 6

In [339]:
obj[['b','c','d']]

b   -7
c    5
d    6
dtype: int64

In [340]:
obj[obj > 0]

a    4
c    5
d    6
dtype: int64

Another way to think about a Series is as a fixed-length, ordered dictionary, as it is a
mapping of index values to data values

In [341]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

obj3 = pd.Series(sdata)

obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [342]:
"Ohio" in obj3

True

In [343]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

When you are only passing a dictionary, the index in the resulting Series will respect
the order of the keys according to the dictionary’s
method, which depends on
keys
the key insertion order. You can override this by passing an index with the dictionary
keys in the order you want them to appear in the resulting Series:

In [344]:
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [345]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [346]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

Series also has these as instance methods:

In [347]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [348]:
obj3,obj4

(Ohio      35000
 Texas     71000
 Oregon    16000
 Utah       5000
 dtype: int64,
 California        NaN
 Ohio          35000.0
 Oregon        16000.0
 Texas         71000.0
 dtype: float64)

In [349]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

Both the Series object itself and its index have a
attribute, which integrates with
name
other areas of pandas functionality:

In [350]:
obj4.name = "population"
obj4.index.name = "state"

print(obj4.name)

print(obj4.index.name)

population
state

In [351]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [352]:
obj

a    4
b   -7
c    5
d    6
dtype: int64

A Series’s index can be altered in place by assignment:

In [353]:
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]

obj

Bob      4
Steve   -7
Jeff     5
Ryan     6
dtype: int64

#### Dataframe

A DataFrame represents a rectangular table of data and contains an ordered, named
collection of columns, each of which can be a different value type (numeric, string,
Boolean, etc.). The DataFrame has both a row and column index; it can be thought of
as a dictionary of Series all sharing the same index.

In [354]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
"year": [2000, 2001, 2002, 2001, 2002, 2003],
"pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)

frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

as with Series,
and the columns are placed according to the order of the keys in
(which
data
depends on their insertion order in the dictionary)

For large DataFrames, the
method selects only the first five rows:
head

In [355]:
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

Similarly, tail returns the last five rows:

In [356]:
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

If you specify a sequence of columns, the DataFrame’s columns will be arranged in
that order

In [357]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop","debt"]) # Missing values are filled with NaN

frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [358]:
frame2["year"]

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [359]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [360]:
type(frame2["year"]), frame2["year"].name, frame2["year"].index, frame2["year"].values

(pandas.Series,
 'year',
 RangeIndex(start=0, stop=6, step=1),
 array([2000, 2001, 2002, 2001, 2002, 2003]))

works for any column name, but
frame2[column]
frame2.column
works only when the column name is a valid Python variable name
and does not conflict with any of the method names in DataFrame

Columns can be modified by assignment. For example, the empty
column could
debt
be assigned a scalar value or an array of values

In [361]:
frame2["debt"] = 16.5

frame2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [362]:
frame2["debt"] = np.arange(6.)

frame2

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

When you are assigning lists or arrays to a column, the value’s length must match the
length of the DataFrame


If you assign a Series, its labels will be realigned exactly to
the DataFrame’s index, inserting missing values in any index values not present:

In [363]:
val = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])

val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [364]:
frame2["debt"] = val

frame2

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

Index labels must match the DataFrame's index to assign a Series to a column

In [365]:
val = pd.Series([-1.2, -1.5, -1.7], index=[0, "four", "five"]) # Index labels must match the DataFrame's index to assign a Series to a column

frame2["debt"] = val

frame2

   year   state  pop  debt
0  2000    Ohio  1.5  -1.2
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

Assigning a column that doesn’t exist will create a new column.

In [366]:

frame2["eastern"] = frame2.state == "Ohio"

frame2

   year   state  pop  debt  eastern
0  2000    Ohio  1.5  -1.2     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2   NaN    False

In [367]:
del frame2["eastern"]

frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='str')

In [368]:
frame2.values

array([[2000, 'Ohio', 1.5, -1.2],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [369]:
state = frame2["state"]

state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: str

In [370]:
state[0] = "New York"


state,frame2

(0    New York
 1        Ohio
 2        Ohio
 3      Nevada
 4      Nevada
 5      Nevada
 Name: state, dtype: str,
    year   state  pop  debt
 0  2000    Ohio  1.5  -1.2
 1  2001    Ohio  1.7   NaN
 2  2002    Ohio  3.6   NaN
 3  2001  Nevada  2.4   NaN
 4  2002  Nevada  2.9   NaN
 5  2003  Nevada  3.2   NaN)

## NOTE

Note on the future of Pandas: If you are using Pandas version 2.0 or newer, Pandas is transitioning to a new system called Copy-on-Write (CoW). When this is enabled, Pandas acts as a safeguard: it starts as a view to save memory, but the second you try to modify the series, it silently creates a copy in the background so your original DataFrame remains untouched.

In [371]:
import pandas as pd

# Create a simple DataFrame
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})

# Extract column 'A' (This creates a VIEW)
my_series = df['A']

# Modify the first element of the extracted Series
my_series[0] = 99 

print(df)

#In pandas 2.0, this will create a copy in the background,
#In pandas 1.5, this will raise an error

#To force a copy, you can use the .copy() method:

my_series = df['A'].copy()

   A  B
0  1  4
1  2  5
2  3  6

##### Nested dictionaries

If the nested dictionary is passed to the DataFrame, pandas will interpret the outer
dictionary keys as the columns, and the inner keys as the row indices:

In [372]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6}, "Nevada": {2001: 2.4, 2002: 2.9, "abc" : "2abc"}}
frame3 = pd.DataFrame(populations)
frame3

      Ohio Nevada
2000   1.5    NaN
2001   1.7    2.4
2002   3.6    2.9
abc    NaN   2abc

In [373]:
frame3.index

Index([2000, 2001, 2002, 'abc'], dtype='object')

The keys in the inner dictionaries are combined to form the index in the result. This
isn’t true if an explicit index is specified:

In [374]:
pd.DataFrame(populations, index=[2001, 2002, 2003])

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

You can transpose the DataFrame (swap rows and columns) with similar syntax to a
NumPy array:

In [375]:
frame3.T

       2000 2001 2002   abc
Ohio    1.5  1.7  3.6   NaN
Nevada  NaN  2.4  2.9  2abc

Note that transposing discards the column data types if the col
umns
do not all have the same data type, so transposing and then
transposing back may lose the previous type information. The col
umns
become arrays of pure Python objects in this case.

In [376]:
frame3["Nevada"]

2000     NaN
2001     2.4
2002     2.9
abc     2abc
Name: Nevada, dtype: object

In [377]:
frame3

      Ohio Nevada
2000   1.5    NaN
2001   1.7    2.4
2002   3.6    2.9
abc    NaN   2abc

Dictionaries of Series are treated in much the same way:

In [378]:
pdata = {"Ohio": frame3["Ohio"][:-1], "Nevada": frame3["Nevada"][:2]}
pd.DataFrame(pdata)

      Ohio Nevada
2000   1.5    NaN
2001   1.7    2.4
2002   3.6    NaN

If a DataFrame’s index and columns have their name attributes set, these will also be
displayed:

Unlike Series, DataFrame does not have a
attribute
name

In [379]:
frame3.index.name = "year"
frame3.columns.name = "state"
frame3

state  Ohio Nevada
year
2000    1.5    NaN
2001    1.7    2.4
2002    3.6    2.9
abc     NaN   2abc

DataFrame’s
to_numpy
method returns the data contained in the DataFrame as a two-dimensional ndarray

In [380]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9],
       [nan, '2abc']], dtype=object)

#### Index Objects

pandas’s Index objects are responsible for holding the axis labels (including a Data.
Frame’s column names) and other metadata (like the axis name or names).

In [381]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])

In [382]:
index  = obj.index

print(index)

print(index[1:])

Index(['a', 'b', 'c'], dtype='str')
Index(['b', 'c'], dtype='str')

Index objects are immutable

In [383]:
try:
    index[1] = "d" # This will raise an error
except Exception as e:
    print(e)

Index does not support mutable operations

Creating a index

In [384]:
labels = pd.Index(np.arange(3))
labels

Index([0, 1, 2], dtype='int64')

In [385]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
print(obj2)
print(obj2.index is labels)

0    1.5
1   -2.5
2    0.0
dtype: float64
True

In [386]:
frame3

state  Ohio Nevada
year
2000    1.5    NaN
2001    1.7    2.4
2002    3.6    2.9
abc     NaN   2abc

In [387]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='str', name='state')

In [388]:
frame3.index

Index([2000, 2001, 2002, 'abc'], dtype='object', name='year')

In [389]:
"Ohio" in frame3.columns,2000 in frame3.index

(True, True)

Unlike Python sets, a pandas Index can contain duplicate labels. Selections with duplicate labels will select all occurrences of that label.

In [390]:
index = pd.Index(["foo", "foo", "bar", "bar"])
index

Index(['foo', 'foo', 'bar', 'bar'], dtype='str')

In [391]:
index.is_unique, index.unique()

(False, Index(['foo', 'bar'], dtype='str'))

#### Reindexing

An important method on pandas objects is reindex, which means to create a new
object with the values rearranged to align with the new index.

In [392]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

Calling
on this Series rearranges the data according to the new index,
reindex
introducing missing values if any index values were not already present:

In [393]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

For ordered data like time series, you may want to do some interpolation or filling of
values when reindexing. The
option allows us to do this, using a method such
method
as ffill

In [394]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4]) 
obj3

0      blue
2    purple
4    yellow
dtype: str

In [395]:
obj3.reindex(range(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: str

With DataFrame,
can alter the (row) index, columns, or both. When passed
reindex
only a sequence, it reindexes the rows in the result

In [396]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
index=["a", "c", "d"],
columns=["Ohio", "Texas", "California"])
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [397]:
frame2 = frame.reindex(["a", "b", "c", "d"])
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

The columns can be reindexed with the columns keyword

In [398]:
states = ["Texas", "Utah", "California"]
frame3 = frame.reindex(columns= states)
frame3 #Because "Ohio" was not in states, the data for that column is dropped from the result

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

Another way to reindex a particular axis is to pass the new axis labels as a positional
argument and then specify the axis to reindex with the
keyword:
axis

In [399]:
frame.reindex(states, axis=1)

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [400]:
frame.reindex(states, axis=0)

            Ohio  Texas  California
Texas        NaN    NaN         NaN
Utah         NaN    NaN         NaN
California   NaN    NaN         NaN

In [401]:
frame.reindex(states, axis="rows")

            Ohio  Texas  California
Texas        NaN    NaN         NaN
Utah         NaN    NaN         NaN
California   NaN    NaN         NaN

In [402]:
frame.reindex(states, axis="index") # same as rows and this is default

            Ohio  Texas  California
Texas        NaN    NaN         NaN
Utah         NaN    NaN         NaN
California   NaN    NaN         NaN

In [403]:
frame.reindex(states, axis="columns")

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [404]:
frame.loc[["a", "d", "c"], ["California", "Texas"]] # reindexing with loc

   California  Texas
a           2      1
d           8      7
c           5      4

#### Dropping Entries from an axis

In [405]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [406]:
new_obj = obj.drop("c")
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [407]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [408]:
obj.drop(["d", "c"])

a    0.0
b    1.0
e    4.0
dtype: float64

With DataFrame, index values can be deleted from either axis. To illustrate this, we
first create an example DataFrame

In [409]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=["Ohio", "Colorado", "Utah", "New York"],
columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [410]:
data.drop(index=["Colorado", "Ohio"])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

You can also drop values from the columns by passing axis=1 (which is like NumPy)
or axis="columns":

In [411]:
data.drop("two", axis=1)

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [412]:
data.drop(columns=["two", "four"])

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [413]:
obj = pd.Series(np.arange(5), index=["a", "b", "c", "d", "e"])

obj

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [414]:
obj['b']

np.int64(1)

In [415]:
try:
    obj[1]
except Exception as e:
    print("This doesn't work in pandas 2.0")

This doesn't work in pandas 2.0

In [416]:
obj[2:4]

c    2
d    3
dtype: int64

In [417]:
obj[["b", "a", "d"]]

b    1
a    0
d    3
dtype: int64

In [418]:
obj[obj < 2]

a    0
b    1
dtype: int64

In [419]:
obj.loc[["b", "a", "d"]]

b    1
a    0
d    3
dtype: int64

The reason to prefer
is because of the different treatment of integers when
loc
indexing with []. Regular []-based indexing will treat integers as labels if the index
contains integers, so the behavior differs depending on the data type of the index. 


Since
operator indexes exclusively with labels, there is also an
operator
loc
iloc
that indexes exclusively with integers to work consistently whether or not the index
contains integers:

You can also slice with labels, but it works differently from normal
Python slicing in that the endpoint is inclusive:

In [420]:
obj.loc["b":"c"]

b    1
c    2
dtype: int64

Assigning values using these methods modifies the corresponding section of the
Series:

In [421]:
obj.loc["b":"c"] = 5

obj

a    0
b    5
c    5
d    3
e    4
dtype: int64

In [422]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=["Ohio", "Colorado", "Utah", "New York"],
columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

Indexing into a DataFrame retrieves one or more columns either with a single value
or sequence

In [423]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [425]:
data.index

Index(['Ohio', 'Colorado', 'Utah', 'New York'], dtype='str')

In [427]:
data[["three", "one"]]

          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

The row selection syntax
is provided as a convenience. Passing a single
data[:2]
element or a list to the
operator selects columns.
[]

In [428]:
data[:2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [443]:
data[-1:]

          one  two  three  four
New York   12   13     14    15

In [444]:
data.iloc[[2, 1]]

          one  two  three  four
Utah        8    9     10    11
Colorado    4    5      6     7

In [445]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [446]:
type(data.iloc[2, [3, 0, 1]])

pandas.Series

In [ ]:
data.iloc[[1, 2], [3, 0, 1]]

          four  one  two
Colorado     7    4    5
Utah        11    8    9

In [450]:
data.iloc[[1, 2], [3, 0, 1]]

          four  one  two
Colorado     7    4    5
Utah        11    8    9

In [456]:
data.iloc[:, :3]

          one  two  three
Ohio        0    1      2
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

Both indexing functions work with slices in addition to single labels or lists of labels:

In [455]:
data.loc[: "Ohio", "one"]

Ohio    0
Name: one, dtype: int64

In [460]:
data.loc[: ,["one"]]

          one
Ohio        0
Colorado    4
Utah        8
New York   12

Boolean arrays can be used with
but not iloc:
loc

In [461]:
data.loc[data.three >= 2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
try:
    data.iloc[data.three >= 2]
except Exception as e:
    print(e)

ValueError: iLocation based boolean indexing cannot use an indexable as a mask